import os


ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
POLYGON_API_KEY = os.getenv("POLYGON_API_KEY")
FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY")
ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
FRED_API_KEY = os.getenv("FRED_API_KEY")
AGENT_API_KEY = os.getenv("AGENT_API_KEY")
FMP_API_KEY = os.getenv("FMP_API_KEY")
COINGECKO_API_KEY = os.getenv("COINGECKO_API_KEY")
CMC_API_KEY = os.getenv("CMC_API_KEY")
ALTFINS_API_KEY = os.getenv("ALTFINS_API_KEY")
XAI_API_KEY = os.getenv("XAI_API_KEY") or os.getenv("GROK_API_KEY")
GROK_API_KEY = XAI_API_KEY  # Alias for convenience
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TWELVEDATA_API_KEY = os.getenv("TWELVEDATA_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
BRAVE_API_KEY = os.getenv("BRAVE_API_KEY")
PERPLEXITY_API_KEY = os.getenv("PERPLEXITY_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
PUBLIC_COM_API_KEY = os.getenv("PUBLIC_COM_API_KEY")
TRADIER_API_KEY = os.getenv("TRADIER_API_KEY")
TRADIER_SANDBOX = os.getenv("TRADIER_SANDBOX", "false").lower() in ("true", "1", "yes")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
TAOSTATS_API_KEY = os.getenv("TAOSTATS_API_KEY")
TAOAPP_API_KEY = os.getenv("TAOAPP_API_KEY")

# ── Perplexity safety flags (all default False) ───────────────────────────────
# Background loops (briefing precompute, whale watch, insider AI daily loop)
PERPLEXITY_BACKGROUND_ENABLED = os.getenv("PERPLEXITY_BACKGROUND_ENABLED", "false").lower() in ("true", "1", "yes")
# Per-page-load enrichment (Pre-IPO Watchlist company enrichment)
PERPLEXITY_PAGELOAD_ENABLED   = os.getenv("PERPLEXITY_PAGELOAD_ENABLED",   "false").lower() in ("true", "1", "yes")
# Silent fallback paths (watchlist ticker news when RSS is empty)
PERPLEXITY_FALLBACK_ENABLED   = os.getenv("PERPLEXITY_FALLBACK_ENABLED",   "false").lower() in ("true", "1", "yes")
