"""Curated anchor bottleneck data for Amazon (AMZN) — all 10 layers."""
from __future__ import annotations

_ANCHOR_DATA: dict = {
    "anchor_name": "Amazon",
    "anchor_description": (
        "Amazon 2025 capex $128.3B (AWS tech infra ~$96.5B; shipping/logistics >$102B). "
        "AWS dual-track: Nvidia frontier GPUs (P6 instances) + Trainium/Inferentia custom ASICs. "
        "Confirmed: Talen Energy 1,920MW nuclear deal, GE Vernova grid partnership, Corning "
        "multiyear fiber deal, Bloom Energy/AEP fuel cells, Iberdrola/ENGIE/Ørsted renewable PPAs, "
        "Rivian 100K EDVs, Sun Country/Cargojet Amazon Air."
    ),
    "nodes": [

        # ── Layer 1: AWS AI Compute / Accelerators ────────────────────────────
        {"ticker": "NVDA", "company_name": "Nvidia",
         "layer": 1, "supply_chain_role": "GPU supply for AWS P6 instances (Blackwell) and AI training clusters",
         "bottleneck_score": 98, "evidence_grade": "A",
         "evidence_grade_reason": "Nvidia Blackwell GPUs confirmed for AWS P6 EC2 instances and Amazon AI cluster expansion.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "gpu_supply"],
         "evidence": ["AWS P6 instances (Blackwell GPUs) announced; Amazon among largest Nvidia customers."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "TSM", "company_name": "TSMC",
         "tradingview_symbol": "TWSE:2330",
         "layer": 1, "supply_chain_role": "Advanced foundry for Trainium/Inferentia ASICs and Nvidia Blackwell",
         "bottleneck_score": 96, "evidence_grade": "A",
         "evidence_grade_reason": "TSMC manufactures Amazon Trainium/Inferentia at advanced nodes; sole foundry for Blackwell.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "foundry", "custom_silicon"],
         "evidence": ["TSMC foundry for Amazon Trainium/Inferentia custom ASICs and Nvidia Blackwell GPUs for AWS."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "3661.TW", "company_name": "Alchip Technologies",
         "tradingview_symbol": "TWSE:3661",
         "layer": 1, "supply_chain_role": "ASIC design partner for Amazon Trainium/Inferentia custom silicon",
         "bottleneck_score": 92, "evidence_grade": "B",
         "evidence_grade_reason": "Alchip is the ASIC design services partner for Amazon Trainium and Inferentia chips.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["ai_compute", "custom_silicon"],
         "evidence": ["Alchip Technologies confirmed ASIC design partner for Amazon Trainium/Inferentia."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "MRVL", "company_name": "Marvell Technology",
         "layer": 1, "supply_chain_role": "Custom ASIC design IP and high-speed connectivity for Amazon AI silicon",
         "bottleneck_score": 90, "evidence_grade": "B",
         "evidence_grade_reason": "Marvell provides SerDes IP and ASIC building blocks used in Amazon custom silicon programs.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["ai_compute", "custom_silicon", "ai_networking"],
         "evidence": ["Marvell ASIC IP and SerDes used in Amazon custom AI chip designs."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "6669.TW", "company_name": "Wiwynn",
         "tradingview_symbol": "TWSE:6669",
         "layer": 1, "supply_chain_role": "AI server rack integration for AWS Trainium/Inferentia compute clusters",
         "bottleneck_score": 90, "evidence_grade": "B",
         "evidence_grade_reason": "Wiwynn designs and manufactures server rack systems for Amazon AWS custom AI clusters.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "ai_servers"],
         "evidence": ["Wiwynn AI server rack manufacturing for AWS Trainium/Inferentia cluster deployments."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "000660.KS", "company_name": "SK Hynix",
         "tradingview_symbol": "KRX:000660",
         "layer": 1, "supply_chain_role": "HBM3E primary supply for Nvidia Blackwell used in AWS P6",
         "bottleneck_score": 88, "evidence_grade": "B",
         "evidence_grade_reason": "SK Hynix HBM3E is the primary memory in Nvidia Blackwell GPUs deployed in AWS P6.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "hbm_memory"],
         "evidence": ["SK Hynix HBM3E in Nvidia Blackwell GPUs powering AWS P6 AI instances."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "005930.KS", "company_name": "Samsung Electronics",
         "tradingview_symbol": "KRX:005930",
         "layer": 1, "supply_chain_role": "HBM second-source; DRAM and NAND for AWS server fleet",
         "bottleneck_score": 87, "evidence_grade": "B",
         "evidence_grade_reason": "Samsung supplies HBM and DRAM/NAND across AWS AI server infrastructure.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "hbm_memory", "dram_nand"],
         "evidence": ["Samsung DRAM/NAND and HBM supply for Amazon AWS AI and general compute."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "MU", "company_name": "Micron Technology",
         "layer": 1, "supply_chain_role": "HBM3E and DRAM/NAND supply for AWS AI compute fleet",
         "bottleneck_score": 86, "evidence_grade": "B",
         "evidence_grade_reason": "Micron HBM3E for Blackwell and DRAM/NAND for AWS server fleet.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "hbm_memory", "dram_nand"],
         "evidence": ["Micron HBM3E and DRAM/NAND supply across AWS AI server infrastructure."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "AMD", "company_name": "AMD",
         "layer": 1, "supply_chain_role": "Instinct GPUs and EPYC CPUs for AWS EC2 compute instances",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "AMD EPYC CPUs power AWS EC2 instances; AMD Instinct GPUs deployed in AWS AI clusters.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "gpu_supply"],
         "evidence": ["AMD EPYC CPUs in AWS Graviton-complementary instances; Instinct GPUs in AI clusters."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "INTC", "company_name": "Intel",
         "layer": 1, "supply_chain_role": "Xeon CPUs for AWS general-purpose EC2 instances and legacy workloads",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Intel Xeon powers AWS EC2 instances alongside AMD EPYC and Amazon Graviton.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "enterprise_compute"],
         "evidence": ["Intel Xeon supply for AWS EC2 general-purpose instance families."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        {"ticker": "ARM", "company_name": "Arm Holdings",
         "layer": 1, "supply_chain_role": "ISA license for Amazon Graviton ARM-based EC2 CPUs",
         "bottleneck_score": 76, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon Graviton processors (Graviton4) are Arm-based custom CPUs for AWS EC2.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["ai_compute", "custom_silicon"],
         "evidence": ["Arm ISA licensed for Amazon Graviton4 custom CPU; most cost-efficient AWS instance type."],
         "category_name": "AWS AI Compute & Accelerators", "category_order": 1},

        # ── Layer 2: Advanced Packaging / HBM / Semi Equipment ────────────────
        {"ticker": "ASML", "company_name": "ASML",
         "layer": 2, "supply_chain_role": "EUV lithography for TSMC advanced nodes producing Trainium/Inferentia",
         "bottleneck_score": 86, "evidence_grade": "B",
         "evidence_grade_reason": "ASML EUV is the sole enabler of TSMC N3/N2 nodes that produce Amazon custom AI chips.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["ASML EUV monopoly on advanced lithography for TSMC Trainium/Inferentia nodes."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "AMAT", "company_name": "Applied Materials",
         "layer": 2, "supply_chain_role": "CVD/PVD deposition equipment for TSMC advanced nodes and HBM",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "Applied Materials tools are critical to TSMC advanced node and HBM production.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["AMAT deposition tools at TSMC for Trainium/Inferentia and HBM manufacturing."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "LRCX", "company_name": "Lam Research",
         "layer": 2, "supply_chain_role": "Etch equipment for advanced node and HBM TSV stacking",
         "bottleneck_score": 83, "evidence_grade": "B",
         "evidence_grade_reason": "Lam etch systems are critical for TSMC N3/N2 and HBM TSV processing for AWS AI chips.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["Lam Research etch tools for TSMC advanced node and HBM TSV processing for Amazon AI silicon."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "KLAC", "company_name": "KLA Corporation",
         "layer": 2, "supply_chain_role": "Process control and inspection for TSMC advanced node yield",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "KLA inspection tools drive yield management at TSMC for Trainium/Inferentia production.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["KLA process control for TSMC Trainium/Inferentia yield management."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "8035.T", "company_name": "Tokyo Electron",
         "tradingview_symbol": "TSE:8035",
         "layer": 2, "supply_chain_role": "Coater/developer and thermal processing equipment for TSMC",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "TEL track and thermal systems are required at TSMC N3/N2 for Amazon AI silicon.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["Tokyo Electron coater/developer tools at TSMC advanced node lines for Trainium."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "6857.T", "company_name": "Advantest",
         "tradingview_symbol": "TSE:6857",
         "layer": 2, "supply_chain_role": "ATE test systems for AI chip and HBM test and burn-in",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Advantest T2000/V93000 test platforms used for Trainium/Inferentia and HBM qualification.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["Advantest test systems for Amazon Trainium/Inferentia and HBM validation."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "TER", "company_name": "Teradyne",
         "layer": 2, "supply_chain_role": "ATE platform for memory and SoC test in AWS AI supply chain",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Teradyne memory and SoC test platforms used in HBM and AI chip supply chain for AWS.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["Teradyne ATE for memory and custom SoC testing in AWS Trainium supply chain."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "ASX", "company_name": "ASE Technology",
         "tradingview_symbol": "TWSE:3711",
         "layer": 2, "supply_chain_role": "OSAT and advanced packaging for Amazon AI chips",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "ASE Technology provides advanced packaging for Trainium/Inferentia and other AI chips.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "osat"],
         "evidence": ["ASE OSAT advanced packaging for Amazon Trainium/Inferentia chip assembly."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "AMKR", "company_name": "Amkor Technology",
         "layer": 2, "supply_chain_role": "Advanced packaging and OSAT for AI chip supply chain",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Amkor provides advanced packaging services for AI chips in Amazon's supply chain.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "osat"],
         "evidence": ["Amkor advanced packaging for AI chips in Amazon AWS supply chain."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "BESI.AS", "company_name": "BE Semiconductor Industries",
         "tradingview_symbol": "EURONEXT:BESI",
         "layer": 2, "supply_chain_role": "Hybrid bonding die-attach equipment for CoWoS/SoIC production",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "BESI hybrid bonding equipment is critical for TSMC CoWoS used in Trainium/Inferentia.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["BESI die bonders for TSMC SoIC and CoWoS packaging of Amazon Trainium ASICs."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "4062.T", "company_name": "Ibiden",
         "tradingview_symbol": "TSE:4062",
         "layer": 2, "supply_chain_role": "IC substrates (ABF) for AI chip packages in AWS supply chain",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Ibiden ABF substrates used for Trainium/Inferentia and Nvidia Blackwell packages.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "ic_substrates"],
         "evidence": ["Ibiden ABF substrate supply for Amazon Trainium/Inferentia and Nvidia Blackwell packages."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "3037.TW", "company_name": "Unimicron Technology",
         "tradingview_symbol": "TWSE:3037",
         "layer": 2, "supply_chain_role": "IC substrates (ABF) for AWS AI chip packages",
         "bottleneck_score": 79, "evidence_grade": "B",
         "evidence_grade_reason": "Unimicron supplies ABF substrates for AI chip packages destined for AWS clusters.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "ic_substrates"],
         "evidence": ["Unimicron ABF substrate supply for AI chip packaging in Amazon AWS supply chain."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "8046.TW", "company_name": "Nan Ya PCB",
         "tradingview_symbol": "TWSE:8046",
         "layer": 2, "supply_chain_role": "PCB and substrate supply for AI servers in AWS supply chain",
         "bottleneck_score": 76, "evidence_grade": "C",
         "evidence_grade_reason": "Nan Ya PCB supplies circuit boards for AI server systems in Amazon AWS.",
         "relationship_specificity": "category_proxy",
         "themes": ["advanced_packaging", "ic_substrates"],
         "evidence": ["Nan Ya PCB supply for AI server PCBs in Amazon AWS infrastructure."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "3189.TW", "company_name": "Kinsus",
         "tradingview_symbol": "TWSE:3189",
         "layer": 2, "supply_chain_role": "IC substrates for AI chip packages in AWS supply chain",
         "bottleneck_score": 75, "evidence_grade": "C",
         "evidence_grade_reason": "Kinsus IC substrates used in AI chip packaging for Amazon AWS.",
         "relationship_specificity": "category_proxy",
         "themes": ["advanced_packaging", "ic_substrates"],
         "evidence": ["Kinsus IC substrate supply for AI chip packaging in Amazon AWS supply chain."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        {"ticker": "6146.T", "company_name": "DISCO Corporation",
         "tradingview_symbol": "TSE:6146",
         "layer": 2, "supply_chain_role": "Dicing and grinding equipment for HBM and chip-on-wafer processing",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "DISCO dicing saws are essential for HBM and CoWoS processing in Amazon AI supply chain.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["DISCO dicing/grinding tools for HBM and CoWoS processing for Amazon AI chips."],
         "category_name": "Advanced Packaging & Semi Equipment", "category_order": 2},

        # ── Layer 3: AI Servers / ODMs / Hardware Assembly ────────────────────
        {"ticker": "6669.TW", "company_name": "Wiwynn",
         "tradingview_symbol": "TWSE:6669",
         "layer": 3, "supply_chain_role": "Primary hyperscale AI server rack ODM for AWS compute clusters",
         "bottleneck_score": 90, "evidence_grade": "B",
         "evidence_grade_reason": "Wiwynn is a primary server ODM designing and manufacturing AWS AI cluster hardware.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Wiwynn AI server rack ODM for AWS Trainium/Inferentia and Nvidia Blackwell clusters."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "2317.TW", "company_name": "Hon Hai / Foxconn",
         "tradingview_symbol": "TWSE:2317",
         "layer": 3, "supply_chain_role": "AI server and rack assembly for AWS compute infrastructure",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "Foxconn manufactures AI server systems and racks for AWS AI cluster deployments.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Foxconn AI server manufacturing for AWS AI cluster infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "2382.TW", "company_name": "Quanta Computer",
         "tradingview_symbol": "TWSE:2382",
         "layer": 3, "supply_chain_role": "AI server ODM for AWS compute clusters",
         "bottleneck_score": 83, "evidence_grade": "B",
         "evidence_grade_reason": "Quanta Computer is a key AI server ODM for AWS alongside Wiwynn.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Quanta Computer AI server ODM supply for AWS AI compute clusters."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "3231.TW", "company_name": "Wistron",
         "tradingview_symbol": "TWSE:3231",
         "layer": 3, "supply_chain_role": "AI server system assembly for AWS compute infrastructure",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "Wistron assembles AI servers for AWS hyperscale AI cluster deployments.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Wistron AI server assembly for AWS infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "JBL", "company_name": "Jabil",
         "layer": 3, "supply_chain_role": "EMS for AI server components and data center hardware",
         "bottleneck_score": 75, "evidence_grade": "B",
         "evidence_grade_reason": "Jabil provides EMS for data center and AI server hardware in Amazon supply chain.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Jabil EMS for AI server hardware manufacturing in Amazon AWS supply chain."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "FLEX", "company_name": "Flex Ltd",
         "layer": 3, "supply_chain_role": "EMS for data center and AI server hardware",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Flex EMS exposure to AI server hardware manufacturing for AWS.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Flex EMS services for AI server manufacturing in Amazon AWS supply chain."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "CLS", "company_name": "Celestica",
         "layer": 3, "supply_chain_role": "ODMO AI server and rack design and manufacturing for hyperscalers",
         "bottleneck_score": 72, "evidence_grade": "B",
         "evidence_grade_reason": "Celestica provides ODMO design and manufacturing for AI server racks for AWS.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Celestica ODMO AI server rack services for AWS infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "SMCI", "company_name": "Super Micro Computer",
         "layer": 3, "supply_chain_role": "Liquid-cooled AI server systems for AWS AI data centers",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Super Micro liquid-cooled AI server systems deployed in AWS AI data centers.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "liquid_cooling"],
         "evidence": ["SMCI liquid-cooled AI servers in AWS AI data center deployments."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "DELL", "company_name": "Dell Technologies",
         "layer": 3, "supply_chain_role": "PowerEdge servers for AWS enterprise workloads and hybrid cloud",
         "bottleneck_score": 68, "evidence_grade": "C",
         "evidence_grade_reason": "Dell PowerEdge servers supply AWS infrastructure for enterprise and hybrid workloads.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "enterprise_compute"],
         "evidence": ["Dell PowerEdge server supply for AWS infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "HPE", "company_name": "Hewlett Packard Enterprise",
         "layer": 3, "supply_chain_role": "Servers and Slingshot networking for AWS HPC instances",
         "bottleneck_score": 66, "evidence_grade": "C",
         "evidence_grade_reason": "HPE server and networking supply for AWS HPC and enterprise workloads.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "enterprise_compute"],
         "evidence": ["HPE server and networking supply for AWS HPC compute infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        {"ticker": "0992.HK", "company_name": "Lenovo",
         "tradingview_symbol": "HKEX:992",
         "layer": 3, "supply_chain_role": "Server supply for AWS enterprise compute and hybrid cloud",
         "bottleneck_score": 66, "evidence_grade": "C",
         "evidence_grade_reason": "Lenovo server exposure to Amazon AWS enterprise compute and hybrid cloud.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "enterprise_compute"],
         "evidence": ["Lenovo server supply for Amazon AWS enterprise and hybrid cloud workloads."],
         "category_name": "AI Servers & ODMs", "category_order": 3},

        # ── Layer 4: Fiber / Optical Networking / Network Silicon ─────────────
        {"ticker": "GLW", "company_name": "Corning",
         "layer": 4, "supply_chain_role": "Fiber optic cable — multiyear supply deal with Amazon for AWS infrastructure",
         "bottleneck_score": 93, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed multiyear Corning fiber optic supply agreement for AWS data center networking.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "fiber_optic"],
         "evidence": ["Amazon-Corning multiyear fiber optic supply agreement disclosed by both companies."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "AVGO", "company_name": "Broadcom",
         "layer": 4, "supply_chain_role": "Ethernet switching silicon for AWS AI cluster networking",
         "bottleneck_score": 85, "evidence_grade": "B",
         "evidence_grade_reason": "Broadcom Tomahawk/Jericho switching silicon deployed in AWS AI cluster Ethernet fabric.",
         "relationship_specificity": "critical_upstream",
         "themes": ["optical_networking", "ai_networking"],
         "evidence": ["Broadcom Ethernet switching silicon in AWS AI cluster network fabric."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "MRVL", "company_name": "Marvell Technology",
         "layer": 4, "supply_chain_role": "PAM4 DSPs and optical interconnect silicon for AWS data centers",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "Marvell PAM4 DSPs and networking chips deployed in AWS optical interconnect systems.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["optical_networking", "ai_networking"],
         "evidence": ["Marvell optical networking chips in AWS data center interconnects."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "COHR", "company_name": "Coherent Corp",
         "layer": 4, "supply_chain_role": "800G/1.6T optical transceivers for AWS AI cluster networking",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "Coherent optical transceivers deployed in AWS AI cluster optical interconnects.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["Coherent 800G/1.6T optical transceiver supply for AWS AI cluster networking."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "CRDO", "company_name": "Credo Technology",
         "layer": 4, "supply_chain_role": "Active electrical cables and SerDes for AWS cluster high-speed interconnects",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Credo AEC solutions deployed in AWS AI cluster high-speed copper interconnects.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "ai_networking"],
         "evidence": ["Credo AEC cables in AWS AI cluster interconnect deployments."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "APH", "company_name": "Amphenol",
         "layer": 4, "supply_chain_role": "Connectors and cable assemblies for AWS AI server networking and power",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Amphenol high-speed connectors and cable assemblies used throughout AWS AI rack infrastructure.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "cables_connectors"],
         "evidence": ["Amphenol high-speed connectors in AWS AI server rack and networking infrastructure."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "LITE", "company_name": "Lumentum Holdings",
         "layer": 4, "supply_chain_role": "Lasers and optical components for AWS-destined optical transceivers",
         "bottleneck_score": 79, "evidence_grade": "B",
         "evidence_grade_reason": "Lumentum laser components supply chain upstream of AWS optical interconnect transceivers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["Lumentum laser supply for optical transceivers deployed in AWS networking."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "FN", "company_name": "Fabrinet",
         "layer": 4, "supply_chain_role": "Contract manufacturing for optical transceivers used by AWS",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Fabrinet manufactures optical transceivers for Coherent, Lumentum deployed in AWS.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["Fabrinet contract manufacturing for AWS optical transceiver supply chain."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "ALAB", "company_name": "Astera Labs",
         "layer": 4, "supply_chain_role": "PCIe retimers and CXL connectivity for AWS AI server architecture",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Astera Labs PCIe retimers embedded in AWS AI server platforms.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "pcie_cxl"],
         "evidence": ["Astera Labs Aries retimers in AI server platforms deployed in AWS."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "TEL", "company_name": "TE Connectivity",
         "layer": 4, "supply_chain_role": "High-speed connectors and cabling for AWS AI server infrastructure",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "TE Connectivity connectors used throughout AWS AI server and power distribution.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "cables_connectors"],
         "evidence": ["TE Connectivity connectors in AWS AI server and networking infrastructure."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "ANET", "company_name": "Arista Networks",
         "layer": 4, "supply_chain_role": "Ethernet switching systems for AWS AI cluster networking",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Arista Ethernet switching deployed in AWS AI cluster networking fabric.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "ai_networking"],
         "evidence": ["Arista switching fabric deployed in AWS AI cluster Ethernet networking."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "PRY.MI", "company_name": "Prysmian",
         "tradingview_symbol": "MTA:PRY",
         "layer": 4, "supply_chain_role": "Fiber optic cable manufacturing for hyperscale data center networks",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Prysmian fiber optic cable supply for hyperscale data center connectivity including AWS.",
         "relationship_specificity": "category_proxy",
         "themes": ["optical_networking", "fiber_optic"],
         "evidence": ["Prysmian fiber optic cable supply for hyperscale data centers including AWS."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "CIEN", "company_name": "Ciena",
         "layer": 4, "supply_chain_role": "WAN optical transport equipment for AWS global backbone network",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Ciena optical transport deployed in AWS global WAN backbone connectivity.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "wan_transport"],
         "evidence": ["Ciena optical transport in AWS global WAN backbone network infrastructure."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "CSCO", "company_name": "Cisco",
         "layer": 4, "supply_chain_role": "Enterprise and campus networking at Amazon headquarters and fulfillment facilities",
         "bottleneck_score": 66, "evidence_grade": "C",
         "evidence_grade_reason": "Cisco enterprise networking supplies Amazon corporate and fulfillment center connectivity.",
         "relationship_specificity": "category_proxy",
         "themes": ["optical_networking", "enterprise_compute"],
         "evidence": ["Cisco enterprise networking at Amazon corporate and fulfillment facilities."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        {"ticker": "COMM", "company_name": "CommScope",
         "layer": 4, "supply_chain_role": "Cable management and fiber infrastructure for AWS data centers",
         "bottleneck_score": 63, "evidence_grade": "C",
         "evidence_grade_reason": "CommScope provides structured cabling for AWS data center fiber infrastructure.",
         "relationship_specificity": "category_proxy",
         "themes": ["optical_networking", "fiber_optic"],
         "evidence": ["CommScope structured cabling and fiber management in AWS data centers."],
         "category_name": "Fiber, Optical & Network Silicon", "category_order": 4},

        # ── Layer 5: Power, Grid, Cooling, Electrical Gear ────────────────────
        {"ticker": "TLN", "company_name": "Talen Energy",
         "layer": 5, "supply_chain_role": "1,920MW nuclear behind-the-meter power — direct Amazon/AWS data center deal",
         "bottleneck_score": 95, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed 1,920MW nuclear power deal with Talen Energy for AWS data centers.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "nuclear_power"],
         "evidence": ["Amazon-Talen Energy 1,920MW nuclear power deal for AWS Susquehanna data center campus."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "GEV", "company_name": "GE Vernova",
         "layer": 5, "supply_chain_role": "Grid infrastructure partnership — confirmed direct Amazon deal for AWS power",
         "bottleneck_score": 94, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed GE Vernova grid infrastructure partnership for AWS data center power supply.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "power_generation"],
         "evidence": ["Amazon-GE Vernova grid infrastructure partnership for AWS data center power."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "SU.PA", "company_name": "Schneider Electric",
         "tradingview_symbol": "EURONEXT:SU",
         "layer": 5, "supply_chain_role": "Power and cooling systems for AWS data center infrastructure",
         "bottleneck_score": 89, "evidence_grade": "B",
         "evidence_grade_reason": "Schneider Electric EcoStruxure deployed in AWS data center power and cooling infrastructure.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Schneider Electric power/cooling EcoStruxure systems deployed across AWS data centers."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "ETN", "company_name": "Eaton Corporation",
         "layer": 5, "supply_chain_role": "UPS and power management infrastructure for AWS data centers",
         "bottleneck_score": 88, "evidence_grade": "B",
         "evidence_grade_reason": "Eaton UPS systems and switchgear deployed across Amazon AWS data center campuses.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Eaton UPS and switchgear in Amazon AWS data center power infrastructure."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "VRT", "company_name": "Vertiv Holdings",
         "layer": 5, "supply_chain_role": "Power/thermal/UPS and liquid cooling for AWS AI data centers",
         "bottleneck_score": 88, "evidence_grade": "B",
         "evidence_grade_reason": "Vertiv liquid cooling and PDU systems deployed across AWS AI data center campuses.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "liquid_cooling"],
         "evidence": ["Vertiv power and cooling infrastructure across AWS data center fleet."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "BE", "company_name": "Bloom Energy",
         "layer": 5, "supply_chain_role": "Fuel cell power generation — confirmed Amazon data center deployment",
         "bottleneck_score": 85, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed Bloom Energy fuel cell deployment for AWS data center power supplementation.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "fuel_cells"],
         "evidence": ["Amazon-Bloom Energy fuel cell deployment at AWS data centers confirmed."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "AEP", "company_name": "American Electric Power",
         "layer": 5, "supply_chain_role": "Grid power supply and Bloom Energy fuel cell host utility — confirmed",
         "bottleneck_score": 84, "evidence_grade": "A",
         "evidence_grade_reason": "AEP confirmed as Amazon AWS grid power supplier and Bloom fuel cell deployment partner.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "grid_power"],
         "evidence": ["AEP grid power supply and Bloom Energy fuel cell deployment for Amazon AWS data centers."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "ABB", "company_name": "ABB",
         "tradingview_symbol": "SWX:ABB",
         "layer": 5, "supply_chain_role": "Automation and electrification equipment for AWS data center power",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "ABB electrical and automation equipment deployed in AWS data center power distribution.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["ABB electrification and automation in AWS data center power infrastructure."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "SIE.DE", "company_name": "Siemens",
         "tradingview_symbol": "XETR:SIE",
         "layer": 5, "supply_chain_role": "Electrical and automation infrastructure for AWS data centers globally",
         "bottleneck_score": 83, "evidence_grade": "B",
         "evidence_grade_reason": "Siemens electrical switchgear and BMS systems deployed in AWS data centers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Siemens electrical infrastructure and BMS in AWS global data centers."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "LR.PA", "company_name": "Legrand",
         "tradingview_symbol": "EURONEXT:LR",
         "layer": 5, "supply_chain_role": "Power distribution and cabinet solutions for AWS data center racks",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Legrand rack PDUs and data center power distribution deployed in AWS facilities.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Legrand rack PDU and power distribution in AWS data center facilities."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "NVT", "company_name": "nVent Electric",
         "layer": 5, "supply_chain_role": "Electrical enclosures and liquid cooling for AWS rack power distribution",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "nVent enclosures and busbar systems in AWS AI rack power distribution.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["nVent enclosures and busbar in AWS AI rack power distribution."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "HUBB", "company_name": "Hubbell",
         "layer": 5, "supply_chain_role": "Electrical components and wiring devices for AWS data center construction",
         "bottleneck_score": 77, "evidence_grade": "B",
         "evidence_grade_reason": "Hubbell electrical components used in AWS data center construction.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Hubbell electrical infrastructure components in AWS data center builds."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "POWL", "company_name": "Powell Industries",
         "layer": 5, "supply_chain_role": "Medium-voltage switchgear for AWS data center electrical distribution",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Powell switchgear in AWS data center MV electrical distribution systems.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Powell Industries switchgear in AWS hyperscale data center electrical distribution."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "HPS.A.TO", "company_name": "Hammond Power Solutions",
         "tradingview_symbol": "TSX:HPS.A",
         "layer": 5, "supply_chain_role": "Custom transformers for AWS data center power distribution",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Hammond Power custom transformers supply hyperscale data center electrical infrastructure.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Hammond Power custom transformer supply for hyperscale data centers including AWS."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "RR.L", "company_name": "Rolls-Royce Holdings",
         "tradingview_symbol": "LSE:RR",
         "layer": 5, "supply_chain_role": "Small modular reactors — potential AWS nuclear power supply",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Rolls-Royce SMR technology is a candidate for AWS data center direct nuclear power.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "nuclear_power"],
         "evidence": ["Rolls-Royce SMR technology in discussions for hyperscale data center nuclear power including AWS."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "ATKR", "company_name": "Atkore",
         "layer": 5, "supply_chain_role": "Electrical conduit and cable management for AWS data center construction",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Atkore electrical conduit and cable management used in hyperscale data center builds.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Atkore conduit and cable management in AWS data center construction."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "CAT", "company_name": "Caterpillar",
         "layer": 5, "supply_chain_role": "Backup diesel/gas generator sets for AWS data center critical power",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Caterpillar large generator sets provide critical backup power at AWS data center campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "backup_power"],
         "evidence": ["Caterpillar gensets for critical backup power at AWS data center campuses."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "CMI", "company_name": "Cummins",
         "layer": 5, "supply_chain_role": "Generator sets for AWS data center backup power",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Cummins generator sets provide backup power for AWS data centers globally.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "backup_power"],
         "evidence": ["Cummins gensets for AWS data center backup power globally."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "2308.TW", "company_name": "Delta Electronics",
         "tradingview_symbol": "TWSE:2308",
         "layer": 5, "supply_chain_role": "Power supply units and thermal management for AWS server hardware",
         "bottleneck_score": 77, "evidence_grade": "B",
         "evidence_grade_reason": "Delta Electronics PSUs and thermal systems deployed in AWS AI server hardware.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "battery_power"],
         "evidence": ["Delta Electronics PSU supply for Amazon AWS server infrastructure."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "6367.T", "company_name": "Daikin",
         "tradingview_symbol": "TSE:6367",
         "layer": 5, "supply_chain_role": "HVAC and chiller systems for AWS data center cooling",
         "bottleneck_score": 76, "evidence_grade": "C",
         "evidence_grade_reason": "Daikin HVAC and chiller systems supply AWS data center facility cooling globally.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Daikin HVAC and precision cooling for AWS data center facility management."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "MOD", "company_name": "Modine Manufacturing",
         "layer": 5, "supply_chain_role": "Liquid cooling and data center thermal management for AWS",
         "bottleneck_score": 73, "evidence_grade": "B",
         "evidence_grade_reason": "Modine data center liquid cooling CDUs deployed in AWS AI data centers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Modine liquid cooling CDUs for AWS AI data center thermal management."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "JCI", "company_name": "Johnson Controls",
         "layer": 5, "supply_chain_role": "Building management and cooling for AWS data center facilities",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Johnson Controls BMS and chiller systems in AWS data center facility management.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Johnson Controls BMS and chiller supply for AWS data center facilities."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "TT", "company_name": "Trane Technologies",
         "layer": 5, "supply_chain_role": "HVAC and precision cooling for AWS data center thermal management",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Trane HVAC and precision air cooling deployed in AWS data center facilities.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Trane HVAC precision cooling in AWS data center facility thermal management."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "ORA", "company_name": "Ormat Technologies",
         "layer": 5, "supply_chain_role": "Geothermal power for AWS data centers in geothermal-available regions",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Ormat geothermal power supply for AWS data centers in geothermally active regions.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "renewable_energy"],
         "evidence": ["Ormat geothermal power exposure to AWS renewable energy demand."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "FLNC", "company_name": "Fluence Energy",
         "layer": 5, "supply_chain_role": "Battery energy storage systems for AWS renewable energy integration",
         "bottleneck_score": 69, "evidence_grade": "C",
         "evidence_grade_reason": "Fluence BESS deployed to support AWS renewable energy integration and grid stability.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "battery_storage"],
         "evidence": ["Fluence battery storage for AWS renewable energy integration at data center sites."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        {"ticker": "GNRC", "company_name": "Generac Holdings",
         "layer": 5, "supply_chain_role": "Industrial generators for AWS edge and secondary data center sites",
         "bottleneck_score": 68, "evidence_grade": "C",
         "evidence_grade_reason": "Generac industrial generators for backup power at smaller AWS edge and secondary sites.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "backup_power"],
         "evidence": ["Generac generators at AWS secondary and edge data center facilities."],
         "category_name": "Power, Grid & Cooling", "category_order": 5},

        # ── Layer 6: Renewable Energy / Clean Power PPAs ──────────────────────
        {"ticker": "IBE.MC", "company_name": "Iberdrola",
         "tradingview_symbol": "BME:IBE",
         "layer": 6, "supply_chain_role": "Renewable energy PPAs — confirmed direct Amazon clean power deal",
         "bottleneck_score": 73, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed renewable energy PPA with Iberdrola for AWS data center clean power.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["Amazon-Iberdrola renewable energy PPA for AWS data center power confirmed."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "AES", "company_name": "AES Corporation",
         "layer": 6, "supply_chain_role": "Clean power and renewable energy — confirmed Amazon data center PPA",
         "bottleneck_score": 72, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed AES clean energy PPA for AWS data center power supply.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["Amazon-AES clean energy PPA for AWS data center power confirmed."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "ENGI.PA", "company_name": "ENGIE",
         "tradingview_symbol": "EURONEXT:ENGI",
         "layer": 6, "supply_chain_role": "Renewable energy — confirmed Amazon European AWS clean power deal",
         "bottleneck_score": 71, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed ENGIE renewable energy supply agreement for AWS European data centers.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["Amazon-ENGIE renewable energy deal for AWS European data center power confirmed."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "NEE", "company_name": "NextEra Energy",
         "layer": 6, "supply_chain_role": "Renewable energy capacity for AWS clean power demand",
         "bottleneck_score": 70, "evidence_grade": "B",
         "evidence_grade_reason": "NextEra renewable capacity services AWS data center clean energy demand.",
         "relationship_specificity": "strong_proxy",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["NextEra renewable energy exposure to Amazon AWS clean power demand."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "ORSTED.CO", "company_name": "Ørsted",
         "tradingview_symbol": "OMXCOP:ORSTED",
         "layer": 6, "supply_chain_role": "Offshore wind — confirmed Amazon European renewable energy PPA",
         "bottleneck_score": 68, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed Ørsted offshore wind PPA for AWS European clean energy.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["Amazon-Ørsted offshore wind PPA for AWS European data center clean energy confirmed."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "BEP", "company_name": "Brookfield Renewable",
         "layer": 6, "supply_chain_role": "Large-scale renewable energy portfolio with hyperscale PPA exposure",
         "bottleneck_score": 67, "evidence_grade": "B",
         "evidence_grade_reason": "Brookfield Renewable renewable energy PPAs service hyperscale demand including Amazon.",
         "relationship_specificity": "strong_proxy",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["Brookfield Renewable PPA exposure to Amazon AWS clean energy demand."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "EDPR.LS", "company_name": "EDP Renováveis",
         "tradingview_symbol": "EURONEXT:EDPR",
         "layer": 6, "supply_chain_role": "Wind and solar renewable energy PPAs for Amazon in Europe/US",
         "bottleneck_score": 66, "evidence_grade": "B",
         "evidence_grade_reason": "EDPR renewable energy PPAs serve Amazon data center clean power needs in Europe and US.",
         "relationship_specificity": "strong_proxy",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["EDPR wind/solar PPA supply for Amazon data center clean energy in Europe/US."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        {"ticker": "RWE.DE", "company_name": "RWE",
         "tradingview_symbol": "XETR:RWE",
         "layer": 6, "supply_chain_role": "Offshore wind and renewable energy for Amazon European AWS data centers",
         "bottleneck_score": 65, "evidence_grade": "B",
         "evidence_grade_reason": "RWE renewable energy supply for Amazon AWS European data center clean power.",
         "relationship_specificity": "strong_proxy",
         "themes": ["renewable_energy", "datacenter_power"],
         "evidence": ["RWE offshore wind/renewable PPA for Amazon AWS European data centers."],
         "category_name": "Renewable Energy PPAs", "category_order": 6},

        # ── Layer 7: Data-Center Construction / Electrical Labor / Materials ───
        {"ticker": "PWR", "company_name": "Quanta Services",
         "layer": 7, "supply_chain_role": "Electrical and grid infrastructure construction for AWS data center campuses",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Quanta provides transmission and electrical construction EPC for AWS data center campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction", "grid_infrastructure"],
         "evidence": ["Quanta EPC services for grid and electrical construction at AWS data center sites."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "EME", "company_name": "EMCOR Group",
         "layer": 7, "supply_chain_role": "M&E construction and electrical for AWS data center builds",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "EMCOR M&E construction services for hyperscale data center builds including AWS.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["EMCOR M&E construction at AWS data center campus builds."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "MTZ", "company_name": "MasTec",
         "layer": 7, "supply_chain_role": "Electrical and energy infrastructure construction for AWS data centers",
         "bottleneck_score": 70, "evidence_grade": "B",
         "evidence_grade_reason": "MasTec electrical infrastructure construction for hyperscale data center campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction", "grid_infrastructure"],
         "evidence": ["MasTec energy infrastructure construction for hyperscale data centers including AWS."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "J", "company_name": "Jacobs Solutions",
         "layer": 7, "supply_chain_role": "Engineering program management for Amazon AWS data center builds",
         "bottleneck_score": 68, "evidence_grade": "B",
         "evidence_grade_reason": "Jacobs engineering program management for AWS large-scale data center construction.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Jacobs Solutions engineering and program management for AWS data center builds."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "ACM", "company_name": "AECOM",
         "layer": 7, "supply_chain_role": "Engineering design and construction management for AWS campuses",
         "bottleneck_score": 68, "evidence_grade": "B",
         "evidence_grade_reason": "AECOM engineering design services for Amazon AWS data center campus development.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["AECOM engineering design for Amazon AWS data center campus development."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "FLR", "company_name": "Fluor Corporation",
         "layer": 7, "supply_chain_role": "EPC services for large-scale AWS data center and infrastructure builds",
         "bottleneck_score": 66, "evidence_grade": "C",
         "evidence_grade_reason": "Fluor EPC services for large infrastructure projects including AWS data centers.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Fluor EPC exposure to AWS large-scale data center construction programs."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "FIX", "company_name": "Comfort Systems USA",
         "layer": 7, "supply_chain_role": "HVAC and mechanical construction for AWS data center facilities",
         "bottleneck_score": 64, "evidence_grade": "B",
         "evidence_grade_reason": "Comfort Systems mechanical contracting for HVAC in hyperscale data center builds.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Comfort Systems HVAC mechanical construction in AWS data center projects."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "STRL", "company_name": "Sterling Infrastructure",
         "layer": 7, "supply_chain_role": "Site development and civil construction for AWS data center campuses",
         "bottleneck_score": 62, "evidence_grade": "C",
         "evidence_grade_reason": "Sterling civil construction for hyperscale data center campus site development.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Sterling Infrastructure civil construction for AWS data center campus development."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "NUE", "company_name": "Nucor",
         "layer": 7, "supply_chain_role": "Structural steel for Amazon AWS data center facility construction",
         "bottleneck_score": 60, "evidence_grade": "C",
         "evidence_grade_reason": "Nucor structural steel consumed in large-scale data center construction.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Nucor structural steel supply for AWS data center facility construction."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "STLD", "company_name": "Steel Dynamics",
         "layer": 7, "supply_chain_role": "Structural steel for Amazon AWS data center builds",
         "bottleneck_score": 59, "evidence_grade": "C",
         "evidence_grade_reason": "Steel Dynamics structural steel consumed in hyperscale data center construction.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Steel Dynamics structural steel for AWS data center construction."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "VMC", "company_name": "Vulcan Materials",
         "layer": 7, "supply_chain_role": "Construction aggregates for Amazon AWS data center campus sites",
         "bottleneck_score": 58, "evidence_grade": "C",
         "evidence_grade_reason": "Vulcan aggregates supplied to data center construction sites including AWS campuses.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Vulcan aggregates for AWS data center campus construction."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "MLM", "company_name": "Martin Marietta Materials",
         "layer": 7, "supply_chain_role": "Construction aggregates for AWS data center campus development",
         "bottleneck_score": 58, "evidence_grade": "C",
         "evidence_grade_reason": "Martin Marietta aggregates used in AWS hyperscale data center campus construction.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Martin Marietta aggregates for Amazon AWS data center campus builds."],
         "category_name": "Construction & Grid", "category_order": 7},

        {"ticker": "CRH", "company_name": "CRH plc",
         "layer": 7, "supply_chain_role": "Construction materials for AWS data center campus infrastructure",
         "bottleneck_score": 57, "evidence_grade": "C",
         "evidence_grade_reason": "CRH construction materials (cement, aggregates) for AWS hyperscale campus builds.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["CRH construction materials exposure to AWS hyperscale campus development."],
         "category_name": "Construction & Grid", "category_order": 7},

        # ── Layer 8: Fulfillment, Delivery, Air Cargo, Freight ────────────────
        {"ticker": "RIVN", "company_name": "Rivian",
         "layer": 8, "supply_chain_role": "Electric delivery vehicles — 100,000 EDV order with Amazon; confirmed",
         "bottleneck_score": 70, "evidence_grade": "A",
         "evidence_grade_reason": "Amazon confirmed 100,000 Rivian electric delivery van order for last-mile delivery.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["logistics", "electric_vehicles"],
         "evidence": ["Amazon 100,000 Rivian electric delivery vehicle order confirmed; delivery underway."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "SNCY", "company_name": "Sun Country Airlines",
         "layer": 8, "supply_chain_role": "Amazon Air cargo — confirmed charter agreement for dedicated freight",
         "bottleneck_score": 68, "evidence_grade": "A",
         "evidence_grade_reason": "Sun Country Airlines operates Amazon Air charter cargo flights under confirmed agreement.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["logistics", "air_cargo"],
         "evidence": ["Sun Country Airlines Amazon Air cargo charter agreement confirmed."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "BA", "company_name": "Boeing",
         "layer": 8, "supply_chain_role": "737-800BCF freighter aircraft for Amazon Air fleet",
         "bottleneck_score": 62, "evidence_grade": "B",
         "evidence_grade_reason": "Boeing 737-800BCF freighters are the primary aircraft in Amazon Air's cargo fleet.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "air_cargo"],
         "evidence": ["Boeing 737-800BCF freighters in Amazon Air cargo fleet."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "CJT.TO", "company_name": "Cargojet",
         "tradingview_symbol": "TSX:CJT",
         "layer": 8, "supply_chain_role": "Amazon Air cargo — confirmed dedicated Canadian air freight agreement",
         "bottleneck_score": 58, "evidence_grade": "A",
         "evidence_grade_reason": "Cargojet confirmed as Amazon Air Canada cargo partner with dedicated freighter operations.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["logistics", "air_cargo"],
         "evidence": ["Cargojet Amazon Air Canada cargo agreement confirmed; anchor customer relationship."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "ALK", "company_name": "Alaska Air Group",
         "layer": 8, "supply_chain_role": "Amazon Air cargo operations — confirmed air freight partner",
         "bottleneck_score": 57, "evidence_grade": "A",
         "evidence_grade_reason": "Alaska Air/Horizon Air operates Amazon Air freighter flights under confirmed partnership.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["logistics", "air_cargo"],
         "evidence": ["Alaska Air/Horizon Air Amazon Air cargo partnership confirmed."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "UPS", "company_name": "UPS",
         "layer": 8, "supply_chain_role": "Third-party parcel delivery for Amazon last-mile and marketplace",
         "bottleneck_score": 56, "evidence_grade": "B",
         "evidence_grade_reason": "UPS provides supplemental parcel delivery for Amazon marketplace orders.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "parcel_delivery"],
         "evidence": ["UPS supplemental parcel delivery for Amazon marketplace shipments."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "FDX", "company_name": "FedEx",
         "layer": 8, "supply_chain_role": "Third-party parcel and freight delivery for Amazon marketplace",
         "bottleneck_score": 55, "evidence_grade": "B",
         "evidence_grade_reason": "FedEx provides express and freight delivery for Amazon marketplace orders.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "parcel_delivery"],
         "evidence": ["FedEx delivery services for Amazon marketplace and third-party seller fulfillment."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "DPW.DE", "company_name": "DHL Group",
         "tradingview_symbol": "XETR:DPW",
         "layer": 8, "supply_chain_role": "International parcel and freight for Amazon global operations",
         "bottleneck_score": 54, "evidence_grade": "B",
         "evidence_grade_reason": "DHL provides international parcel and freight delivery for Amazon global marketplace.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "parcel_delivery"],
         "evidence": ["DHL international delivery for Amazon global marketplace and AWS infrastructure."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "MAERSK-B.CO", "company_name": "A.P. Moller-Maersk B",
         "tradingview_symbol": "OMXCOP:MAERSK-B",
         "layer": 8, "supply_chain_role": "Container shipping for Amazon global supply chain",
         "bottleneck_score": 53, "evidence_grade": "B",
         "evidence_grade_reason": "Maersk container shipping services supply Amazon's global product import supply chain.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "container_shipping"],
         "evidence": ["Maersk container shipping for Amazon global product import and supply chain."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "CHRW", "company_name": "C.H. Robinson",
         "layer": 8, "supply_chain_role": "Third-party logistics and freight brokerage for Amazon supply chain",
         "bottleneck_score": 52, "evidence_grade": "C",
         "evidence_grade_reason": "C.H. Robinson provides freight brokerage and 3PL services for Amazon supply chain.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "freight_brokerage"],
         "evidence": ["C.H. Robinson 3PL/freight brokerage for Amazon supply chain."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "JBHT", "company_name": "J.B. Hunt Transport",
         "layer": 8, "supply_chain_role": "Dedicated truckload and intermodal for Amazon distribution",
         "bottleneck_score": 52, "evidence_grade": "C",
         "evidence_grade_reason": "J.B. Hunt provides dedicated truckload and intermodal services for Amazon distribution network.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "trucking"],
         "evidence": ["J.B. Hunt dedicated trucking and intermodal for Amazon fulfillment network."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "XPO", "company_name": "XPO",
         "layer": 8, "supply_chain_role": "LTL freight for Amazon marketplace and B2B delivery",
         "bottleneck_score": 51, "evidence_grade": "C",
         "evidence_grade_reason": "XPO LTL freight services for Amazon marketplace B2B delivery.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "freight"],
         "evidence": ["XPO LTL freight for Amazon marketplace B2B fulfillment."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "GXO", "company_name": "GXO Logistics",
         "layer": 8, "supply_chain_role": "Contract logistics and warehouse automation for Amazon",
         "bottleneck_score": 51, "evidence_grade": "C",
         "evidence_grade_reason": "GXO contract logistics services for Amazon fulfillment and warehouse operations.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "warehouse"],
         "evidence": ["GXO contract logistics for Amazon fulfillment operations."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "ODFL", "company_name": "Old Dominion Freight Line",
         "layer": 8, "supply_chain_role": "LTL freight for Amazon marketplace seller shipping",
         "bottleneck_score": 50, "evidence_grade": "C",
         "evidence_grade_reason": "Old Dominion LTL services for Amazon marketplace third-party seller shipping.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "freight"],
         "evidence": ["ODFL LTL services for Amazon marketplace seller shipping network."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "UNP", "company_name": "Union Pacific",
         "layer": 8, "supply_chain_role": "Rail intermodal for Amazon western US distribution network",
         "bottleneck_score": 48, "evidence_grade": "C",
         "evidence_grade_reason": "Union Pacific rail intermodal services for Amazon western US distribution.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "rail"],
         "evidence": ["Union Pacific intermodal rail for Amazon western US distribution logistics."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        {"ticker": "CSX", "company_name": "CSX",
         "layer": 8, "supply_chain_role": "Rail intermodal for Amazon eastern US distribution network",
         "bottleneck_score": 48, "evidence_grade": "C",
         "evidence_grade_reason": "CSX rail intermodal services for Amazon eastern US distribution.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "rail"],
         "evidence": ["CSX intermodal rail for Amazon eastern US distribution logistics."],
         "category_name": "Fulfillment & Logistics", "category_order": 8},

        # ── Layer 9: Warehouse Automation / Robotics / Scanning ───────────────
        {"ticker": "HON", "company_name": "Honeywell",
         "layer": 9, "supply_chain_role": "Warehouse scanning, controls and building automation for Amazon fulfillment",
         "bottleneck_score": 64, "evidence_grade": "A",
         "evidence_grade_reason": "Honeywell barcode scanners and controls are confirmed in Amazon fulfillment center operations.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Honeywell scanning and controls systems confirmed in Amazon fulfillment centers."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "ZBRA", "company_name": "Zebra Technologies",
         "layer": 9, "supply_chain_role": "Barcode scanners and mobile devices for Amazon fulfillment operations",
         "bottleneck_score": 56, "evidence_grade": "B",
         "evidence_grade_reason": "Zebra barcode scanners and TC-series mobile devices used in Amazon fulfillment centers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Zebra barcode scanners and mobile computers in Amazon fulfillment center operations."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "CGNX", "company_name": "Cognex",
         "layer": 9, "supply_chain_role": "Machine vision for Amazon automated warehouse and package sorting",
         "bottleneck_score": 54, "evidence_grade": "B",
         "evidence_grade_reason": "Cognex machine vision systems used in Amazon fulfillment center package scanning and sorting.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Cognex machine vision in Amazon package scanning and sorting automation."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "6201.T", "company_name": "Toyota Industries",
         "tradingview_symbol": "TSE:6201",
         "layer": 9, "supply_chain_role": "Forklifts and material handling for Amazon fulfillment centers",
         "bottleneck_score": 53, "evidence_grade": "B",
         "evidence_grade_reason": "Toyota Industries forklifts and pallet trucks used in Amazon fulfillment center operations.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Toyota Industries material handling equipment in Amazon fulfillment centers."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "KGX.DE", "company_name": "KION Group",
         "tradingview_symbol": "XETR:KGX",
         "layer": 9, "supply_chain_role": "Warehouse automation systems and forklifts for Amazon fulfillment",
         "bottleneck_score": 52, "evidence_grade": "B",
         "evidence_grade_reason": "KION warehouse automation (Dematic) and forklifts (Linde) used in Amazon fulfillment centers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["KION Dematic automation and Linde forklifts in Amazon fulfillment center operations."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "ROK", "company_name": "Rockwell Automation",
         "layer": 9, "supply_chain_role": "Industrial automation controls for Amazon fulfillment center operations",
         "bottleneck_score": 50, "evidence_grade": "C",
         "evidence_grade_reason": "Rockwell Automation industrial controls used in Amazon fulfillment center automation.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Rockwell Automation controls in Amazon fulfillment center industrial systems."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "6861.T", "company_name": "Keyence",
         "tradingview_symbol": "TSE:6861",
         "layer": 9, "supply_chain_role": "Sensors and barcode readers for Amazon production line automation",
         "bottleneck_score": 50, "evidence_grade": "C",
         "evidence_grade_reason": "Keyence sensors and laser scanners used in Amazon fulfillment center automated lines.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Keyence sensors and laser scanners in Amazon fulfillment center automation."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "HY", "company_name": "Hyster-Yale",
         "layer": 9, "supply_chain_role": "Heavy forklifts and lift trucks for Amazon distribution centers",
         "bottleneck_score": 48, "evidence_grade": "C",
         "evidence_grade_reason": "Hyster-Yale heavy lift trucks used in Amazon distribution center operations.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Hyster-Yale heavy lift trucks in Amazon distribution centers."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "SYM", "company_name": "Symbotic",
         "layer": 9, "supply_chain_role": "AI-powered warehouse automation robots for Amazon/Walmart fulfillment",
         "bottleneck_score": 45, "evidence_grade": "C",
         "evidence_grade_reason": "Symbotic autonomous warehouse robots deployed in large-scale fulfillment operations.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["Symbotic autonomous warehouse robots in large-scale fulfillment operations relevant to Amazon."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        {"ticker": "AUTO.OL", "company_name": "AutoStore",
         "tradingview_symbol": "OB:AUTO",
         "layer": 9, "supply_chain_role": "Grid-based automated storage and retrieval for fulfillment centers",
         "bottleneck_score": 44, "evidence_grade": "C",
         "evidence_grade_reason": "AutoStore ASRS systems provide dense automated storage in fulfillment operations.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "warehouse_automation"],
         "evidence": ["AutoStore grid-based ASRS for fulfillment center automation relevant to Amazon."],
         "category_name": "Warehouse Automation & Robotics", "category_order": 9},

        # ── Layer 10: Packaging / Labels / Consumables ────────────────────────
        {"ticker": "IP", "company_name": "International Paper",
         "layer": 10, "supply_chain_role": "Corrugated packaging — confirmed Amazon supply relationship",
         "bottleneck_score": 60, "evidence_grade": "A",
         "evidence_grade_reason": "International Paper supplies corrugated boxes and packaging to Amazon fulfillment centers.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["logistics", "packaging"],
         "evidence": ["International Paper corrugated box and packaging supply for Amazon fulfillment confirmed."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "SEE", "company_name": "Sealed Air",
         "layer": 10, "supply_chain_role": "Protective packaging solutions — confirmed Amazon fulfillment supply",
         "bottleneck_score": 58, "evidence_grade": "A",
         "evidence_grade_reason": "Sealed Air protective packaging (Bubble Wrap, AirCap) confirmed in Amazon fulfillment operations.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["logistics", "packaging"],
         "evidence": ["Sealed Air protective packaging supply for Amazon fulfillment centers confirmed."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "SW", "company_name": "Smurfit Westrock",
         "layer": 10, "supply_chain_role": "Corrugated packaging and paper for Amazon fulfillment",
         "bottleneck_score": 58, "evidence_grade": "B",
         "evidence_grade_reason": "Smurfit Westrock corrugated packaging supply for Amazon fulfillment centers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Smurfit Westrock corrugated packaging supply for Amazon fulfillment network."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "PKG", "company_name": "Packaging Corp of America",
         "layer": 10, "supply_chain_role": "Corrugated boxes and containerboard for Amazon fulfillment",
         "bottleneck_score": 54, "evidence_grade": "B",
         "evidence_grade_reason": "Packaging Corp supplies corrugated containers for Amazon fulfillment operations.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Packaging Corp corrugated box supply for Amazon fulfillment centers."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "AVY", "company_name": "Avery Dennison",
         "layer": 10, "supply_chain_role": "Labels and RFID tags for Amazon fulfillment and inventory management",
         "bottleneck_score": 52, "evidence_grade": "B",
         "evidence_grade_reason": "Avery Dennison labels and RFID supply for Amazon inventory and shipping labels.",
         "relationship_specificity": "strong_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Avery Dennison labels and RFID tags for Amazon inventory and shipping operations."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "GPK", "company_name": "Graphic Packaging",
         "layer": 10, "supply_chain_role": "Paper-based packaging for Amazon grocery and food delivery",
         "bottleneck_score": 50, "evidence_grade": "C",
         "evidence_grade_reason": "Graphic Packaging supplies paper-based packaging for Amazon Fresh and grocery delivery.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Graphic Packaging paper packaging for Amazon Fresh grocery delivery operations."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "SON", "company_name": "Sonoco Products",
         "layer": 10, "supply_chain_role": "Protective and industrial packaging for Amazon supply chain",
         "bottleneck_score": 49, "evidence_grade": "C",
         "evidence_grade_reason": "Sonoco packaging supply for Amazon's product and fulfillment supply chain.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Sonoco protective packaging in Amazon's product supply chain."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "AMCR", "company_name": "Amcor",
         "layer": 10, "supply_chain_role": "Flexible packaging for Amazon private label and grocery operations",
         "bottleneck_score": 48, "evidence_grade": "C",
         "evidence_grade_reason": "Amcor flexible packaging supply for Amazon private label and fresh food operations.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Amcor flexible packaging for Amazon private label and grocery supply chain."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "ATR", "company_name": "AptarGroup",
         "layer": 10, "supply_chain_role": "Dispensing and dosage packaging for Amazon health and beauty",
         "bottleneck_score": 42, "evidence_grade": "C",
         "evidence_grade_reason": "AptarGroup dispensing systems for Amazon health, beauty and pharmaceutical packaging.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["AptarGroup dispensing packaging for Amazon health and beauty product supply."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "UFPT", "company_name": "UFP Technologies",
         "layer": 10, "supply_chain_role": "Custom foam and protective packaging for Amazon fulfillment",
         "bottleneck_score": 43, "evidence_grade": "C",
         "evidence_grade_reason": "UFP Technologies custom foam packaging for protective shipping in Amazon fulfillment.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["UFP Technologies foam protective packaging for Amazon fulfillment operations."],
         "category_name": "Packaging & Consumables", "category_order": 10},

        {"ticker": "PACK", "company_name": "Ranpak Holdings",
         "layer": 10, "supply_chain_role": "Paper-based protective packaging for Amazon last-mile delivery",
         "bottleneck_score": 43, "evidence_grade": "C",
         "evidence_grade_reason": "Ranpak paper-based packaging solutions used in Amazon fulfillment and delivery.",
         "relationship_specificity": "category_proxy",
         "themes": ["logistics", "packaging"],
         "evidence": ["Ranpak paper-based protective packaging for Amazon last-mile delivery operations."],
         "category_name": "Packaging & Consumables", "category_order": 10},
    ],
}
