"""Curated anchor bottleneck data for META Platforms — all 12 layers."""
from __future__ import annotations

_ANCHOR_DATA: dict = {
    "anchor_name": "Meta Platforms",
    "anchor_description": (
        "Meta 2026 capex $125B–$145B. Nvidia Blackwell/GB200/GB300, AMD Instinct (6GW multi-year "
        "agreement), Broadcom MTIA custom silicon (>1GW initial deployment). Confirmed power: "
        "Entergy 5.2GW Louisiana gas plants, NextEra ~2.5GW renewables, Williams gas "
        "infrastructure, CoreWeave $21B+$14.2B capacity, Nebius $12B+$15B."
    ),
    "nodes": [

        # ── Layer 1: AI Compute & Custom Silicon ──────────────────────────────
        {"ticker": "AVGO", "company_name": "Broadcom",
         "layer": 1, "supply_chain_role": "MTIA custom silicon, XPU, Ethernet switching and advanced packaging — deepest Meta dependency",
         "bottleneck_score": 100, "evidence_grade": "A",
         "evidence_grade_reason": "Broadcom co-develops Meta MTIA XPU, supplies Tomahawk/Jericho switching, and leads CoWoS packaging for Meta AI pods — formally disclosed in multiple filings.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "custom_silicon", "ai_networking"],
         "evidence": ["Broadcom MTIA ASIC >1GW initial deployment confirmed; Ethernet switching for AI fabric; advanced packaging."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "AMD", "company_name": "AMD",
         "layer": 1, "supply_chain_role": "Instinct GPU supply — 6GW multi-year agreement with Meta",
         "bottleneck_score": 99, "evidence_grade": "A",
         "evidence_grade_reason": "Meta announced 6GW AMD Instinct GPU supply agreement, formally disclosed.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "gpu_supply"],
         "evidence": ["Meta-AMD 6GW multi-year Instinct GPU supply agreement publicly announced 2025."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "NVDA", "company_name": "Nvidia",
         "layer": 1, "supply_chain_role": "Blackwell/GB200/GB300 GPU supply for Meta AI clusters",
         "bottleneck_score": 98, "evidence_grade": "A",
         "evidence_grade_reason": "Nvidia Blackwell GPUs confirmed as primary AI accelerator for Meta 2025–26 deployments.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_compute", "gpu_supply"],
         "evidence": ["Nvidia Blackwell/GB200/GB300 AI cluster deployments at Meta confirmed."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "TSM", "company_name": "TSMC",
         "tradingview_symbol": "TWSE:2330",
         "layer": 1, "supply_chain_role": "3nm/2nm foundry for MTIA, Blackwell, CoWoS interposer — critical bottleneck",
         "bottleneck_score": 98, "evidence_grade": "A",
         "evidence_grade_reason": "TSMC sole-source foundry for Nvidia Blackwell and Broadcom MTIA; CoWoS advanced packaging for all Meta AI silicon.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "foundry", "advanced_packaging"],
         "evidence": ["TSMC 3nm/CoWoS supply underlies every Meta AI chip — Blackwell, MTIA, and AMD Instinct."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "000660.KS", "company_name": "SK Hynix",
         "tradingview_symbol": "KRX:000660",
         "layer": 1, "supply_chain_role": "HBM3E primary supplier for Nvidia Blackwell destined for Meta",
         "bottleneck_score": 96, "evidence_grade": "A",
         "evidence_grade_reason": "SK Hynix is primary HBM3E supplier for Nvidia GB200/GB300 used in Meta AI clusters.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "hbm_memory"],
         "evidence": ["SK Hynix HBM3E sole/primary source for Blackwell GPUs destined for Meta AI pods."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "MU", "company_name": "Micron Technology",
         "layer": 1, "supply_chain_role": "HBM3E second-source; DRAM and NAND for Meta data centers",
         "bottleneck_score": 92, "evidence_grade": "A",
         "evidence_grade_reason": "Micron ships HBM3E for Nvidia Blackwell and Trainium; DRAM/NAND across Meta AI servers.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "hbm_memory", "dram_nand"],
         "evidence": ["Micron HBM3E production ramping for Blackwell; DRAM/NAND across Meta AI server fleet."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "005930.KS", "company_name": "Samsung Electronics",
         "tradingview_symbol": "KRX:005930",
         "layer": 1, "supply_chain_role": "HBM3/HBM3E third-source; NAND; foundry competition",
         "bottleneck_score": 91, "evidence_grade": "B",
         "evidence_grade_reason": "Samsung competes with SK Hynix on HBM supply and provides NAND for Meta storage.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "hbm_memory", "dram_nand"],
         "evidence": ["Samsung HBM qualification; NAND SSD supply for Meta AI cluster storage."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "MRVL", "company_name": "Marvell Technology",
         "layer": 1, "supply_chain_role": "DSPs, custom silicon IP, and data-center connectivity chips",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "Marvell provides high-speed SerDes IP and custom ASIC building blocks used in Meta AI infrastructure.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_compute", "custom_silicon", "ai_networking"],
         "evidence": ["Marvell DSP/SerDes IP embedded in Meta AI networking and custom silicon designs."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "ARM", "company_name": "Arm Holdings",
         "layer": 1, "supply_chain_role": "CPU instruction-set architecture for MTIA and Meta server CPUs",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Arm ISA underpins Meta's custom silicon and Neoverse server CPU landscape.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_compute", "custom_silicon"],
         "evidence": ["Arm ISA licensed for Meta MTIA CPU elements and third-party server CPUs."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        # Semi tools
        {"ticker": "ASML", "company_name": "ASML",
         "layer": 1, "supply_chain_role": "EUV lithography — sole supplier enabling 3nm/2nm TSMC nodes for Meta AI chips",
         "bottleneck_score": 68, "evidence_grade": "B",
         "evidence_grade_reason": "ASML EUV is the only tool enabling N3/N2 TSMC nodes that produce Meta's AI silicon.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["ASML EUV monopoly on advanced node lithography; prerequisite for all Meta AI silicon."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "AMAT", "company_name": "Applied Materials",
         "layer": 1, "supply_chain_role": "Deposition/etch equipment for TSMC N3/N2 and CoWoS",
         "bottleneck_score": 66, "evidence_grade": "B",
         "evidence_grade_reason": "Applied Materials CVD/PVD tools are critical to TSMC advanced node and CoWoS production.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["AMAT deposition tools critical for TSMC advanced-node and HBM manufacturing."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "LRCX", "company_name": "Lam Research",
         "layer": 1, "supply_chain_role": "Etch and deposition equipment for advanced node and NAND",
         "bottleneck_score": 65, "evidence_grade": "B",
         "evidence_grade_reason": "Lam etch tools critical for TSMC advanced node, HBM stacking, and NAND memory.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["Lam Research etch systems key for TSMC N3/N2 and HBM TSV processing."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "KLAC", "company_name": "KLA Corporation",
         "layer": 1, "supply_chain_role": "Process control and inspection for advanced node yield",
         "bottleneck_score": 64, "evidence_grade": "B",
         "evidence_grade_reason": "KLA inspection tools are required for yield management at N3/N2 TSMC and HBM nodes.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["KLA process control essential for TSMC advanced node yield for Meta AI chips."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "8035.T", "company_name": "Tokyo Electron",
         "tradingview_symbol": "TSE:8035",
         "layer": 1, "supply_chain_role": "Coater/developer and etch equipment for TSMC advanced nodes",
         "bottleneck_score": 63, "evidence_grade": "B",
         "evidence_grade_reason": "TEL track systems are required at TSMC for N3/N2 lithography steps.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["Tokyo Electron coater/developer tools at TSMC advanced node lines."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "6857.T", "company_name": "Advantest",
         "tradingview_symbol": "TSE:6857",
         "layer": 1, "supply_chain_role": "AI chip test equipment — T2000/V93000 for GPU and HBM burn-in",
         "bottleneck_score": 62, "evidence_grade": "B",
         "evidence_grade_reason": "Advantest T2000 testers are used for Nvidia/AMD GPU and SK Hynix HBM final test.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["Advantest T2000/V93000 test systems for Blackwell GPU and HBM3E qualification."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "TER", "company_name": "Teradyne",
         "layer": 1, "supply_chain_role": "ATE platform for memory and SOC test in AI supply chain",
         "bottleneck_score": 61, "evidence_grade": "B",
         "evidence_grade_reason": "Teradyne J750/UltraFlex platforms used in DRAM and SoC test for Meta AI supply chain.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_compute", "semiconductor_tools"],
         "evidence": ["Teradyne memory/SoC ATE used across HBM and AI chip production for Meta."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        {"ticker": "6146.T", "company_name": "DISCO Corporation",
         "tradingview_symbol": "TSE:6146",
         "layer": 1, "supply_chain_role": "Dicing and grinding equipment for advanced packaging and HBM",
         "bottleneck_score": 60, "evidence_grade": "B",
         "evidence_grade_reason": "DISCO dicing saws are essential for HBM wafer singulation and CoWoS processing.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ai_compute", "advanced_packaging"],
         "evidence": ["DISCO dicing/grinding tools used at TSMC CoWoS and SK Hynix HBM lines."],
         "category_name": "AI Compute & Custom Silicon", "category_order": 1},

        # ── Layer 2: Foundry, CoWoS & Packaging ───────────────────────────────
        {"ticker": "ASX", "company_name": "ASE Technology",
         "tradingview_symbol": "TWSE:3711",
         "layer": 2, "supply_chain_role": "OSAT and advanced packaging for Meta AI chip supply chain",
         "bottleneck_score": 83, "evidence_grade": "B",
         "evidence_grade_reason": "ASE is the world's largest OSAT and packages logic and memory ICs in Meta AI servers.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "osat"],
         "evidence": ["ASE Technology OSAT services for AI chip packaging in Meta supply chain."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "AMKR", "company_name": "Amkor Technology",
         "layer": 2, "supply_chain_role": "Advanced packaging and OSAT for AI chip supply chain",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "Amkor provides SiP and advanced packaging for compute components in Meta AI infrastructure.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "osat"],
         "evidence": ["Amkor advanced packaging used in AI chip supply for Meta servers."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "TSEM", "company_name": "Tower Semiconductor",
         "layer": 2, "supply_chain_role": "Specialty foundry for silicon photonics and analog chips",
         "bottleneck_score": 72, "evidence_grade": "B",
         "evidence_grade_reason": "Tower specialty foundry produces silicon photonics ICs used in Meta AI optical interconnects.",
         "relationship_specificity": "category_proxy",
         "themes": ["advanced_packaging", "silicon_photonics"],
         "evidence": ["Tower Semiconductor silicon photonics foundry for optical interconnect chips in Meta AI."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "GFS", "company_name": "GlobalFoundries",
         "layer": 2, "supply_chain_role": "Specialty foundry for RF/mixed-signal silicon photonics chips",
         "bottleneck_score": 72, "evidence_grade": "B",
         "evidence_grade_reason": "GlobalFoundries produces RF and silicon photonics chips used in Meta optical networking.",
         "relationship_specificity": "category_proxy",
         "themes": ["advanced_packaging", "silicon_photonics"],
         "evidence": ["GlobalFoundries RF/photonics foundry exposure to Meta AI networking ICs."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "3037.TW", "company_name": "Unimicron Technology",
         "tradingview_symbol": "TWSE:3037",
         "layer": 2, "supply_chain_role": "IC substrates for Nvidia Blackwell and MTIA packages",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Unimicron supplies ABF substrates for Nvidia and Broadcom chips in Meta AI servers.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "ic_substrates"],
         "evidence": ["Unimicron ABF substrate supply for Nvidia Blackwell and Broadcom MTIA packages."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "4062.T", "company_name": "Ibiden",
         "tradingview_symbol": "TSE:4062",
         "layer": 2, "supply_chain_role": "IC substrates for Nvidia Blackwell GPU packages",
         "bottleneck_score": 77, "evidence_grade": "B",
         "evidence_grade_reason": "Ibiden is a primary ABF substrate supplier for Nvidia GPU packages including Blackwell.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "ic_substrates"],
         "evidence": ["Ibiden ABF substrates for Nvidia Blackwell destined for Meta AI pods."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "BESI.AS", "company_name": "BE Semiconductor Industries",
         "tradingview_symbol": "EURONEXT:BESI",
         "layer": 2, "supply_chain_role": "Hybrid bonding and die-attach equipment for CoWoS/SoIC",
         "bottleneck_score": 58, "evidence_grade": "B",
         "evidence_grade_reason": "BESI die bonders are key equipment for TSMC SoIC and CoWoS hybrid bonding steps.",
         "relationship_specificity": "critical_upstream",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["BESI die-attach/hybrid bonding tools at TSMC SoIC/CoWoS lines."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        {"ticker": "AEHR", "company_name": "Aehr Test Systems",
         "layer": 2, "supply_chain_role": "Burn-in test equipment for silicon photonics and power devices",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Aehr wafer-level burn-in used for silicon photonics and power ICs in Meta AI infrastructure.",
         "relationship_specificity": "category_proxy",
         "themes": ["advanced_packaging", "semiconductor_tools"],
         "evidence": ["Aehr WaferPak burn-in for silicon photonics chips in Meta optical supply chain."],
         "category_name": "Foundry, CoWoS & Packaging", "category_order": 2},

        # ── Layer 3: HBM, Memory & Storage ────────────────────────────────────
        {"ticker": "STX", "company_name": "Seagate Technology",
         "layer": 3, "supply_chain_role": "High-capacity HDD for Meta data lake and cold storage",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Seagate HAMR HDDs supply Meta's cold storage and data lake infrastructure.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["hdd_storage", "datacenter_storage"],
         "evidence": ["Seagate HAMR HDD supply for Meta large-scale cold/warm storage."],
         "category_name": "HBM, Memory & Storage", "category_order": 3},

        {"ticker": "WDC", "company_name": "Western Digital",
         "layer": 3, "supply_chain_role": "HDD and NAND/SSD for Meta AI server and storage systems",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Western Digital supplies HDD and NAND for Meta data center storage.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["hdd_storage", "dram_nand"],
         "evidence": ["Western Digital HDD/NAND supply for Meta data centers confirmed in supply reports."],
         "category_name": "HBM, Memory & Storage", "category_order": 3},

        {"ticker": "285A.T", "company_name": "Kioxia Holdings",
         "tradingview_symbol": "TSE:285A",
         "layer": 3, "supply_chain_role": "NAND flash for Meta AI server storage",
         "bottleneck_score": 68, "evidence_grade": "B",
         "evidence_grade_reason": "Kioxia NAND is supplied into Meta AI servers alongside Samsung and WDC.",
         "relationship_specificity": "critical_upstream",
         "themes": ["dram_nand", "datacenter_storage"],
         "evidence": ["Kioxia NAND flash supply for Meta AI server SSD storage tiers."],
         "category_name": "HBM, Memory & Storage", "category_order": 3},

        # ── Layer 4: AI Networking ─────────────────────────────────────────────
        {"ticker": "ANET", "company_name": "Arista Networks",
         "layer": 4, "supply_chain_role": "Ethernet AI switching fabric — confirmed primary Meta AI network supplier",
         "bottleneck_score": 95, "evidence_grade": "A",
         "evidence_grade_reason": "Arista is disclosed as the primary Ethernet switching vendor for Meta AI cluster networking.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_networking", "ethernet_switching"],
         "evidence": ["Arista 7800/7700 series deployed in Meta AI cluster Ethernet fabric — confirmed by Arista and Meta."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "ALAB", "company_name": "Astera Labs",
         "layer": 4, "supply_chain_role": "PCIe retimers and CXL connectivity for AI server fabric",
         "bottleneck_score": 83, "evidence_grade": "B",
         "evidence_grade_reason": "Astera Labs PCIe 5.0/6.0 retimers and CXL devices are embedded in Nvidia Blackwell platforms.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_networking", "pcie_cxl"],
         "evidence": ["Astera Labs Aries retimers in Nvidia Blackwell DGX/HGX systems used by Meta."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "CRDO", "company_name": "Credo Technology",
         "layer": 4, "supply_chain_role": "Active electrical cables and SerDes for AI cluster networking",
         "bottleneck_score": 83, "evidence_grade": "B",
         "evidence_grade_reason": "Credo AEC and SerDes solutions are embedded in Meta AI cluster interconnects.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_networking", "cables_connectors"],
         "evidence": ["Credo AEC solutions for AI cluster high-speed copper interconnects at Meta."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "APH", "company_name": "Amphenol",
         "layer": 4, "supply_chain_role": "Connectors and cable assemblies for AI cluster networking and power",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "Amphenol high-speed backplane connectors and power connectors used in Meta AI server racks.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_networking", "cables_connectors"],
         "evidence": ["Amphenol high-speed connectors in AI server rack assemblies for Meta clusters."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "TEL", "company_name": "TE Connectivity",
         "layer": 4, "supply_chain_role": "Connectors, sensors and cabling for AI server and power infrastructure",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "TE Connectivity supplies high-speed connectors and power distribution components for Meta AI racks.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_networking", "cables_connectors"],
         "evidence": ["TE Connectivity connectors and cables in Meta AI server and power distribution."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "CSCO", "company_name": "Cisco",
         "layer": 4, "supply_chain_role": "Enterprise and WAN networking infrastructure at Meta data centers",
         "bottleneck_score": 70, "evidence_grade": "B",
         "evidence_grade_reason": "Cisco provides WAN edge and campus networking at Meta, alongside Arista for AI fabric.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_networking", "datacenter_networking"],
         "evidence": ["Cisco WAN and campus networking at Meta data centers."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "MTSI", "company_name": "MACOM Technology Solutions",
         "layer": 4, "supply_chain_role": "Optical and semiconductor connectivity for AI cluster networking",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "MACOM PAM4 DSPs and optical components used in Meta AI interconnect transceivers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_networking", "optical_components"],
         "evidence": ["MACOM optical DSPs and laser drivers in Meta AI cluster transceivers."],
         "category_name": "AI Networking", "category_order": 4},

        {"ticker": "SMTC", "company_name": "Semtech",
         "layer": 4, "supply_chain_role": "Signal integrity and connectivity semiconductor components",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Semtech signal integrity chips used in high-speed connectivity for datacenter networking.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_networking", "signal_integrity"],
         "evidence": ["Semtech signal integrity ICs in AI cluster ethernet and optical links."],
         "category_name": "AI Networking", "category_order": 4},

        # ── Layer 5: Optical Networking ────────────────────────────────────────
        {"ticker": "GLW", "company_name": "Corning",
         "layer": 5, "supply_chain_role": "Fiber optic cable — $6B anchor deal directly confirmed by Meta",
         "bottleneck_score": 94, "evidence_grade": "A",
         "evidence_grade_reason": "Meta confirmed a $6B+ fiber optic supply agreement with Corning for AI data center connectivity.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "fiber_optic"],
         "evidence": ["Meta $6B+ Corning fiber supply agreement disclosed by both companies in 2025."],
         "category_name": "Optical Networking", "category_order": 5},

        {"ticker": "COHR", "company_name": "Coherent Corp",
         "layer": 5, "supply_chain_role": "Optical components, lasers and 800G/1.6T transceivers for Meta AI networking",
         "bottleneck_score": 86, "evidence_grade": "B",
         "evidence_grade_reason": "Coherent supplies optical transceivers and laser components for Meta AI cluster networking.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["Coherent 800G/1.6T optical modules deployed in Meta AI cluster networking."],
         "category_name": "Optical Networking", "category_order": 5},

        {"ticker": "LITE", "company_name": "Lumentum Holdings",
         "layer": 5, "supply_chain_role": "Lasers and optical components for Meta AI networking transceivers",
         "bottleneck_score": 86, "evidence_grade": "B",
         "evidence_grade_reason": "Lumentum supplies pump lasers and VCSEL arrays for Meta-destined optical transceivers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["Lumentum laser components in optical transceivers for Meta AI cluster networking."],
         "category_name": "Optical Networking", "category_order": 5},

        {"ticker": "AAOI", "company_name": "Applied Optoelectronics",
         "layer": 5, "supply_chain_role": "800G optical transceivers for Meta AI cluster networking",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "AAOI produces 800G QSFP-DD transceivers for hyperscale AI cluster deployments including Meta.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["AAOI 800G transceiver supply for Meta AI data center networking confirmed."],
         "category_name": "Optical Networking", "category_order": 5},

        {"ticker": "FN", "company_name": "Fabrinet",
         "layer": 5, "supply_chain_role": "Optical transceiver manufacturing services for Meta networking",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Fabrinet is the contract manufacturer for Coherent, Lumentum, and other transceiver brands used by Meta.",
         "relationship_specificity": "strong_proxy",
         "themes": ["optical_networking", "optical_transceivers"],
         "evidence": ["Fabrinet manufactures transceiver modules for Coherent and Lumentum shipped to Meta."],
         "category_name": "Optical Networking", "category_order": 5},

        {"ticker": "SOI.PA", "company_name": "Soitec",
         "tradingview_symbol": "EURONEXT:SOI",
         "layer": 5, "supply_chain_role": "Engineered SOI substrates for silicon photonics components",
         "bottleneck_score": 75, "evidence_grade": "B",
         "evidence_grade_reason": "Soitec SOI wafers are the substrate for silicon photonics chips in AI optical interconnects.",
         "relationship_specificity": "critical_upstream",
         "themes": ["optical_networking", "silicon_photonics"],
         "evidence": ["Soitec SOI substrates for silicon photonics transceivers in Meta AI networking."],
         "category_name": "Optical Networking", "category_order": 5},

        {"ticker": "HIMX", "company_name": "Himax Technologies",
         "layer": 5, "supply_chain_role": "Display drivers and silicon photonics exposure via WLO lenses",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Himax wafer-level optics used in optical interconnect modules for AI cluster networking.",
         "relationship_specificity": "category_proxy",
         "themes": ["optical_networking", "silicon_photonics"],
         "evidence": ["Himax WLO lens technology for silicon photonics transceivers in AI networking."],
         "category_name": "Optical Networking", "category_order": 5},

        # ── Layer 6: Power Generation & Gas ───────────────────────────────────
        {"ticker": "ETR", "company_name": "Entergy",
         "layer": 6, "supply_chain_role": "5.2GW natural gas generation in Louisiana — largest confirmed Meta power deal",
         "bottleneck_score": 93, "evidence_grade": "A",
         "evidence_grade_reason": "Entergy 5.2GW Louisiana gas generation confirmed by Entergy and Meta in 2025 regulatory filings.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "power_generation"],
         "evidence": ["Entergy 5.2GW gas generation build-out for Meta Louisiana campus — confirmed regulatory filing 2025."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "NEE", "company_name": "NextEra Energy",
         "layer": 6, "supply_chain_role": "~2.5GW renewable PPAs — confirmed Meta clean power agreement",
         "bottleneck_score": 88, "evidence_grade": "A",
         "evidence_grade_reason": "NextEra ~2.5GW renewable energy purchase agreement with Meta confirmed in earnings.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "renewable_energy"],
         "evidence": ["NextEra ~2.5GW renewables PPA with Meta confirmed in NextEra Q1 2025 earnings."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "WMB", "company_name": "Williams Companies",
         "layer": 6, "supply_chain_role": "Natural gas pipeline infrastructure serving Meta Ohio data center campus",
         "bottleneck_score": 88, "evidence_grade": "A",
         "evidence_grade_reason": "Williams gas infrastructure contract with Meta for Ohio datacenter gas supply confirmed.",
         "relationship_specificity": "confirmed_asset_partner",
         "themes": ["datacenter_power", "gas_infrastructure"],
         "evidence": ["Williams natural gas infrastructure agreement with Meta for Ohio data center campus."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "GEV", "company_name": "GE Vernova",
         "layer": 6, "supply_chain_role": "Gas turbines and grid equipment for Meta and utility power build-out",
         "bottleneck_score": 85, "evidence_grade": "B",
         "evidence_grade_reason": "GE Vernova gas turbines supply Entergy and other utilities building power for Meta.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "power_generation"],
         "evidence": ["GE Vernova gas turbines in Entergy Louisiana generation supplying Meta data centers."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "CEG", "company_name": "Constellation Energy",
         "layer": 6, "supply_chain_role": "Nuclear power and clean energy supply for Meta data centers",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Constellation nuclear clean energy supply for Meta data centers via PPA.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "nuclear_power"],
         "evidence": ["Constellation Energy nuclear PPA exposure to Meta data center clean power demand."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "VST", "company_name": "Vistra",
         "layer": 6, "supply_chain_role": "Nuclear and dispatchable generation for AI data center power",
         "bottleneck_score": 75, "evidence_grade": "B",
         "evidence_grade_reason": "Vistra nuclear and gas capacity supplying AI data center power in Texas/central US.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "power_generation"],
         "evidence": ["Vistra nuclear/CCGT power exposure to Meta and hyperscaler data center demand."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "TLN", "company_name": "Talen Energy",
         "layer": 6, "supply_chain_role": "Nuclear behind-the-meter power for hyperscale AI data centers",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Talen Energy nuclear behind-the-meter data center power model is relevant to Meta.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "nuclear_power"],
         "evidence": ["Talen nuclear data center power model applicable to Meta large-campus power demand."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "ET", "company_name": "Energy Transfer",
         "layer": 6, "supply_chain_role": "Natural gas pipeline and midstream infrastructure for Meta data center gas supply",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Energy Transfer pipeline infrastructure services hyperscale gas demand in Texas and Louisiana regions.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "gas_infrastructure"],
         "evidence": ["Energy Transfer midstream natural gas supply chain serving Meta Louisiana/Texas facilities."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        {"ticker": "EQT", "company_name": "EQT Corporation",
         "layer": 6, "supply_chain_role": "Appalachian natural gas production for AI data center gas-fired generation",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "EQT is a major Appalachian gas producer upstream of data center gas-fired power generation.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "gas_infrastructure"],
         "evidence": ["EQT Appalachian gas production feeds power plants serving Meta data centers."],
         "category_name": "Power Generation & Gas", "category_order": 6},

        # ── Layer 7: Electrical Infrastructure ────────────────────────────────
        {"ticker": "VRT", "company_name": "Vertiv Holdings",
         "layer": 7, "supply_chain_role": "Power/thermal/UPS and liquid cooling infrastructure for Meta AI data centers",
         "bottleneck_score": 92, "evidence_grade": "B",
         "evidence_grade_reason": "Vertiv UPS, PDU and thermal management systems are deployed across Meta AI data center campuses.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "liquid_cooling"],
         "evidence": ["Vertiv UPS/PDU/liquid cooling deployed across Meta AI data center campuses."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "ETN", "company_name": "Eaton Corporation",
         "layer": 7, "supply_chain_role": "UPS, switchgear and power management for Meta AI data centers",
         "bottleneck_score": 91, "evidence_grade": "B",
         "evidence_grade_reason": "Eaton UPS systems and switchgear are used in Meta data center power infrastructure.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Eaton UPS and switchgear supply for Meta data center power distribution."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "SU.PA", "company_name": "Schneider Electric",
         "tradingview_symbol": "EURONEXT:SU",
         "layer": 7, "supply_chain_role": "Power/cooling/energy management systems for Meta AI data centers",
         "bottleneck_score": 90, "evidence_grade": "B",
         "evidence_grade_reason": "Schneider EcoStruxure power and cooling systems are used in Meta data center construction.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Schneider Electric EcoStruxure deployed in Meta data center power and cooling."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "2308.TW", "company_name": "Delta Electronics",
         "tradingview_symbol": "TWSE:2308",
         "layer": 7, "supply_chain_role": "Power supplies and thermal management for Meta AI server hardware",
         "bottleneck_score": 79, "evidence_grade": "B",
         "evidence_grade_reason": "Delta Electronics supplies power supply units and thermal systems for Meta AI servers.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["datacenter_power", "battery_power"],
         "evidence": ["Delta Electronics PSU supply for Meta AI server hardware."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "POWL", "company_name": "Powell Industries",
         "layer": 7, "supply_chain_role": "Medium-voltage switchgear for Meta data center electrical distribution",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Powell switchgear used in data center MV electrical distribution for hyperscale campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Powell Industries switchgear in hyperscale data center electrical distribution including Meta."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "HPS.A.TO", "company_name": "Hammond Power Solutions",
         "tradingview_symbol": "TSX:HPS.A",
         "layer": 7, "supply_chain_role": "Custom transformers for data center power distribution",
         "bottleneck_score": 77, "evidence_grade": "B",
         "evidence_grade_reason": "Hammond Power custom transformers supply hyperscale data center electrical infrastructure.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Hammond Power custom transformer supply for hyperscale data center campuses including Meta."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "HUBB", "company_name": "Hubbell",
         "layer": 7, "supply_chain_role": "Electrical infrastructure components for Meta data center construction",
         "bottleneck_score": 75, "evidence_grade": "B",
         "evidence_grade_reason": "Hubbell wiring devices and electrical components used in Meta data center construction.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["Hubbell electrical infrastructure components in Meta data center builds."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "NVT", "company_name": "nVent Electric",
         "layer": 7, "supply_chain_role": "Electrical enclosures and liquid cooling for Meta AI data center PDUs",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "nVent enclosures and busbar systems used in AI rack power distribution for hyperscalers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "electrical_infrastructure"],
         "evidence": ["nVent enclosures and busbar in Meta AI rack power distribution."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "MPWR", "company_name": "Monolithic Power Systems",
         "layer": 7, "supply_chain_role": "Power management ICs for AI server voltage regulation",
         "bottleneck_score": 72, "evidence_grade": "B",
         "evidence_grade_reason": "MPWR VR modules are embedded in AI server boards including Nvidia Blackwell platforms.",
         "relationship_specificity": "critical_upstream",
         "themes": ["datacenter_power", "power_semiconductors"],
         "evidence": ["Monolithic Power VR modules in AI server board designs for Meta clusters."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        {"ticker": "AEIS", "company_name": "Advanced Energy Industries",
         "layer": 7, "supply_chain_role": "Precision power conversion for semiconductor fab equipment and AI server PSUs",
         "bottleneck_score": 73, "evidence_grade": "B",
         "evidence_grade_reason": "Advanced Energy precision power supplies used in semiconductor tools and AI server power.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "semiconductor_tools"],
         "evidence": ["Advanced Energy precision power in semiconductor fabs and AI server power systems."],
         "category_name": "Electrical Infrastructure", "category_order": 7},

        # ── Layer 8: Cooling & Thermal Management ─────────────────────────────
        {"ticker": "CAT", "company_name": "Caterpillar",
         "layer": 8, "supply_chain_role": "Backup generators and on-site power for Meta AI data centers",
         "bottleneck_score": 82, "evidence_grade": "B",
         "evidence_grade_reason": "Caterpillar large diesel/gas generators provide backup power at Meta AI data center campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "backup_power"],
         "evidence": ["Caterpillar diesel/gas generator sets for backup power at Meta AI campuses."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "CMI", "company_name": "Cummins",
         "layer": 8, "supply_chain_role": "Generator sets and power systems for Meta data center backup power",
         "bottleneck_score": 81, "evidence_grade": "B",
         "evidence_grade_reason": "Cummins generator sets provide critical backup power for Meta AI data center facilities.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_power", "backup_power"],
         "evidence": ["Cummins gensets for critical backup power at Meta AI data center sites."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "TT", "company_name": "Trane Technologies",
         "layer": 8, "supply_chain_role": "HVAC and precision cooling for Meta data center thermal management",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Trane HVAC and precision air cooling systems used in Meta data center facilities.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Trane HVAC precision cooling deployed in Meta data center facilities."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "CARR", "company_name": "Carrier Global",
         "layer": 8, "supply_chain_role": "Chiller and HVAC systems for Meta data center cooling",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Carrier chiller systems provide facility cooling at Meta large-scale data center campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Carrier chiller and HVAC systems in Meta data center cooling infrastructure."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "JCI", "company_name": "Johnson Controls",
         "layer": 8, "supply_chain_role": "Building management systems and cooling for Meta data centers",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Johnson Controls BMS and chiller systems are deployed in Meta data center facility management.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Johnson Controls BMS and chiller supply for Meta data center facilities."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "MOD", "company_name": "Modine Manufacturing",
         "layer": 8, "supply_chain_role": "Liquid cooling and data center thermal management solutions",
         "bottleneck_score": 79, "evidence_grade": "B",
         "evidence_grade_reason": "Modine data center liquid cooling and CRAC units used in hyperscale AI data centers.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["Modine liquid cooling CDUs and CRAC units deployed in AI data centers including Meta."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "SPXC", "company_name": "SPX Technologies",
         "layer": 8, "supply_chain_role": "Cooling towers and engineered thermal equipment for data centers",
         "bottleneck_score": 75, "evidence_grade": "B",
         "evidence_grade_reason": "SPX cooling tower products used in data center facility thermal management at hyperscale.",
         "relationship_specificity": "strong_proxy",
         "themes": ["liquid_cooling", "datacenter_cooling"],
         "evidence": ["SPX Technologies cooling towers in Meta data center campus thermal infrastructure."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        {"ticker": "GNRC", "company_name": "Generac Holdings",
         "layer": 8, "supply_chain_role": "On-site backup power generators for data center campuses",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Generac industrial generators provide backup power for mid-scale data center facilities.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_power", "backup_power"],
         "evidence": ["Generac industrial generators for data center backup power at Meta edge/secondary sites."],
         "category_name": "Cooling & Thermal Management", "category_order": 8},

        # ── Layer 9: AI Servers & ODMs ─────────────────────────────────────────
        {"ticker": "2317.TW", "company_name": "Hon Hai / Foxconn",
         "tradingview_symbol": "TWSE:2317",
         "layer": 9, "supply_chain_role": "AI server and rack integration for Meta AI data centers",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "Foxconn/Hon Hai assembles AI server systems and racks for Meta AI infrastructure.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Foxconn AI server rack integration for Meta AI data centers confirmed."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "2382.TW", "company_name": "Quanta Computer",
         "tradingview_symbol": "TWSE:2382",
         "layer": 9, "supply_chain_role": "AI server and rack ODM for Meta compute infrastructure",
         "bottleneck_score": 85, "evidence_grade": "B",
         "evidence_grade_reason": "Quanta Computer is a major AI server ODM supplying Meta AI cluster hardware.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Quanta Computer AI server ODM supply for Meta AI clusters confirmed in supply reports."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "6669.TW", "company_name": "Wiwynn",
         "tradingview_symbol": "TWSE:6669",
         "layer": 9, "supply_chain_role": "Hyperscale AI server systems — Meta affiliate ODM",
         "bottleneck_score": 84, "evidence_grade": "B",
         "evidence_grade_reason": "Wiwynn is a Meta-affiliated ODM designing and manufacturing AI server systems.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Wiwynn hyperscale AI server supply for Meta confirmed; Meta is anchor customer."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "3231.TW", "company_name": "Wistron",
         "tradingview_symbol": "TWSE:3231",
         "layer": 9, "supply_chain_role": "AI server system assembly for Meta AI infrastructure",
         "bottleneck_score": 81, "evidence_grade": "B",
         "evidence_grade_reason": "Wistron assembles AI server systems for Meta compute infrastructure.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Wistron AI server assembly for Meta AI data centers."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "2356.TW", "company_name": "Inventec",
         "tradingview_symbol": "TWSE:2356",
         "layer": 9, "supply_chain_role": "AI server ODM for Meta and other hyperscalers",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Inventec produces AI server systems for hyperscale customers including Meta.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Inventec AI server ODM supply chain for Meta compute infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "4938.TW", "company_name": "Pegatron",
         "tradingview_symbol": "TWSE:4938",
         "layer": 9, "supply_chain_role": "AI server and system assembly for hyperscale data centers",
         "bottleneck_score": 74, "evidence_grade": "C",
         "evidence_grade_reason": "Pegatron expanding into AI server manufacturing for hyperscale customers including Meta.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Pegatron AI server manufacturing ramp for hyperscale AI data center supply."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "0992.HK", "company_name": "Lenovo",
         "tradingview_symbol": "HKEX:992",
         "layer": 9, "supply_chain_role": "AI servers and enterprise compute for Meta data centers",
         "bottleneck_score": 74, "evidence_grade": "C",
         "evidence_grade_reason": "Lenovo TruScale AI infrastructure provides enterprise-grade AI servers in Meta supply chain.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Lenovo AI server exposure to Meta AI infrastructure demand."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "SMCI", "company_name": "Super Micro Computer",
         "layer": 9, "supply_chain_role": "AI server systems with liquid cooling for Meta AI data centers",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Super Micro high-density liquid-cooled AI server systems deployed in Meta AI clusters.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "liquid_cooling"],
         "evidence": ["Super Micro liquid-cooled AI server systems in Meta AI data center deployments."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "DELL", "company_name": "Dell Technologies",
         "layer": 9, "supply_chain_role": "PowerEdge AI servers and enterprise infrastructure for Meta",
         "bottleneck_score": 74, "evidence_grade": "C",
         "evidence_grade_reason": "Dell PowerEdge servers provide AI compute in Meta's hybrid enterprise and AI workloads.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "enterprise_compute"],
         "evidence": ["Dell PowerEdge AI server supply for Meta enterprise and AI workloads."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "HPE", "company_name": "Hewlett Packard Enterprise",
         "layer": 9, "supply_chain_role": "Servers and networking for Meta hybrid cloud and AI infrastructure",
         "bottleneck_score": 74, "evidence_grade": "C",
         "evidence_grade_reason": "HPE ProLiant servers and Slingshot networking used in Meta AI and HPC deployments.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "enterprise_compute"],
         "evidence": ["HPE server and networking supply for Meta AI and HPC infrastructure."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "CLS", "company_name": "Celestica",
         "layer": 9, "supply_chain_role": "AI hardware design and manufacturing services for hyperscalers",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Celestica provides ODMO services for AI server rack systems including for Meta supply chain.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Celestica ODMO AI server manufacturing for hyperscale clients including Meta."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "JBL", "company_name": "Jabil",
         "layer": 9, "supply_chain_role": "EMS for AI server and data center hardware components",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Jabil provides electronics manufacturing services for AI server components in Meta supply chain.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Jabil EMS for AI server hardware manufacturing in Meta supply chain."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "FLEX", "company_name": "Flex Ltd",
         "layer": 9, "supply_chain_role": "EMS for data center and AI server hardware for hyperscalers",
         "bottleneck_score": 72, "evidence_grade": "C",
         "evidence_grade_reason": "Flex provides electronics manufacturing for data center hardware including server components.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Flex EMS exposure to Meta data center server hardware manufacturing."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "SANM", "company_name": "Sanmina",
         "layer": 9, "supply_chain_role": "PCB and system-level EMS for data center networking and servers",
         "bottleneck_score": 68, "evidence_grade": "C",
         "evidence_grade_reason": "Sanmina provides PCB and system integration for networking and server hardware in data centers.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Sanmina EMS for data center networking and server hardware supply to Meta."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        {"ticker": "PLXS", "company_name": "Plexus Corp",
         "layer": 9, "supply_chain_role": "EMS for complex networking and industrial electronics",
         "bottleneck_score": 65, "evidence_grade": "C",
         "evidence_grade_reason": "Plexus provides complex electronics manufacturing for networking infrastructure.",
         "relationship_specificity": "category_proxy",
         "themes": ["ai_servers", "odm_ems"],
         "evidence": ["Plexus EMS for networking and server hardware in Meta infrastructure supply chain."],
         "category_name": "AI Servers & ODMs", "category_order": 9},

        # ── Layer 10: Neocloud / Leased Compute Capacity ───────────────────────
        {"ticker": "CRWV", "company_name": "CoreWeave",
         "layer": 10, "supply_chain_role": "Confirmed $21B + $14.2B additional neocloud GPU capacity for Meta AI",
         "bottleneck_score": 90, "evidence_grade": "A",
         "evidence_grade_reason": "Meta announced $21B CoreWeave contract (2025) plus $14.2B additional capacity — formally disclosed.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["neocloud", "ai_compute"],
         "evidence": ["Meta-CoreWeave $21B compute capacity contract announced 2025; additional $14.2B contract."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "NBIS", "company_name": "Nebius Group",
         "layer": 10, "supply_chain_role": "Confirmed $12B + $15B neocloud GPU capacity deals with Meta",
         "bottleneck_score": 89, "evidence_grade": "A",
         "evidence_grade_reason": "Meta confirmed $12B and $15B Nebius neocloud GPU compute capacity agreements.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["neocloud", "ai_compute"],
         "evidence": ["Nebius $12B + $15B GPU capacity agreements with Meta formally announced."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "ORCL", "company_name": "Oracle",
         "layer": 10, "supply_chain_role": "Cloud infrastructure capacity talks with Meta for AI workloads",
         "bottleneck_score": 80, "evidence_grade": "B",
         "evidence_grade_reason": "Oracle OCI GPU cloud capacity discussions with Meta for AI training overflow.",
         "relationship_specificity": "strong_proxy",
         "themes": ["neocloud", "ai_compute"],
         "evidence": ["Oracle OCI cloud capacity in discussions with Meta for AI workload overflow."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "EQIX", "company_name": "Equinix",
         "layer": 10, "supply_chain_role": "Data center colocation and interconnection for Meta AI edge deployments",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Equinix colocation services used for Meta edge AI inference and interconnection.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["neocloud", "datacenter_colocation"],
         "evidence": ["Equinix colocation for Meta AI edge inference and global interconnection."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "DLR", "company_name": "Digital Realty",
         "layer": 10, "supply_chain_role": "Data center colocation for Meta AI infrastructure overflow",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "Digital Realty colocation capacity used by Meta for AI infrastructure scaling.",
         "relationship_specificity": "strong_proxy",
         "themes": ["neocloud", "datacenter_colocation"],
         "evidence": ["Digital Realty colocation exposure to Meta AI infrastructure demand."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "IRM", "company_name": "Iron Mountain",
         "layer": 10, "supply_chain_role": "Data center and storage colocation with AI capacity build-out",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Iron Mountain data center expansion exposure to hyperscale AI demand including Meta.",
         "relationship_specificity": "category_proxy",
         "themes": ["neocloud", "datacenter_colocation"],
         "evidence": ["Iron Mountain data center capacity growth serving hyperscale AI demand including Meta."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "GDS", "company_name": "GDS Holdings",
         "layer": 10, "supply_chain_role": "Chinese data center colocation for Meta AI demand in Asia",
         "bottleneck_score": 68, "evidence_grade": "C",
         "evidence_grade_reason": "GDS provides colocation for hyperscale AI in China/Asia relevant to Meta's global infrastructure.",
         "relationship_specificity": "category_proxy",
         "themes": ["neocloud", "datacenter_colocation"],
         "evidence": ["GDS data center colocation for hyperscale AI demand in Asia including Meta."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        {"ticker": "VNET", "company_name": "VNET Group",
         "layer": 10, "supply_chain_role": "Chinese carrier-neutral data center colocation for AI workloads",
         "bottleneck_score": 65, "evidence_grade": "C",
         "evidence_grade_reason": "VNET carrier-neutral colocation services for AI workloads in China relevant to Meta's Asia footprint.",
         "relationship_specificity": "category_proxy",
         "themes": ["neocloud", "datacenter_colocation"],
         "evidence": ["VNET colocation exposure to hyperscale AI demand including Meta Asian operations."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        # ── Layer 11: Construction & Grid ──────────────────────────────────────
        {"ticker": "PWR", "company_name": "Quanta Services",
         "layer": 11, "supply_chain_role": "Electrical construction and grid infrastructure for Meta data center campuses",
         "bottleneck_score": 78, "evidence_grade": "B",
         "evidence_grade_reason": "Quanta Services is a primary EPC contractor for transmission grid connecting Meta data center campuses.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction", "grid_infrastructure"],
         "evidence": ["Quanta EPC services for transmission and electrical construction at Meta data center sites."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "EME", "company_name": "EMCOR Group",
         "layer": 11, "supply_chain_role": "Mechanical and electrical construction for Meta data center builds",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "EMCOR provides M&E construction services for hyperscale data center builds including Meta.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["EMCOR M&E construction services at Meta data center campus builds."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "MTZ", "company_name": "MasTec",
         "layer": 11, "supply_chain_role": "Electrical and energy infrastructure construction for Meta data centers",
         "bottleneck_score": 74, "evidence_grade": "B",
         "evidence_grade_reason": "MasTec electrical and energy infrastructure construction exposure to Meta data center builds.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction", "grid_infrastructure"],
         "evidence": ["MasTec energy infrastructure construction for hyperscale data center campuses including Meta."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "J", "company_name": "Jacobs Solutions",
         "layer": 11, "supply_chain_role": "Engineering and construction management for Meta data center programs",
         "bottleneck_score": 72, "evidence_grade": "B",
         "evidence_grade_reason": "Jacobs provides engineering management for large data center construction programs.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Jacobs engineering program management for hyperscale data center projects."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "ACM", "company_name": "AECOM",
         "layer": 11, "supply_chain_role": "Engineering design and program management for Meta data center campus",
         "bottleneck_score": 70, "evidence_grade": "B",
         "evidence_grade_reason": "AECOM engineering design services for Meta data center and campus infrastructure.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["AECOM engineering program management for Meta data center campus development."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "FLR", "company_name": "Fluor Corporation",
         "layer": 11, "supply_chain_role": "EPC services for large-scale data center and energy infrastructure",
         "bottleneck_score": 68, "evidence_grade": "C",
         "evidence_grade_reason": "Fluor EPC services for large infrastructure projects including hyperscale data centers.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Fluor EPC exposure to large-scale data center construction programs."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "FIX", "company_name": "Comfort Systems USA",
         "layer": 11, "supply_chain_role": "HVAC and mechanical construction for Meta data center facilities",
         "bottleneck_score": 68, "evidence_grade": "B",
         "evidence_grade_reason": "Comfort Systems mechanical contracting for HVAC in hyperscale data center builds.",
         "relationship_specificity": "strong_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Comfort Systems HVAC mechanical construction in hyperscale data center projects."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "STRL", "company_name": "Sterling Infrastructure",
         "layer": 11, "supply_chain_role": "Site development and civil construction for Meta data center campuses",
         "bottleneck_score": 66, "evidence_grade": "C",
         "evidence_grade_reason": "Sterling provides site development and civil work for hyperscale data center campus development.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction"],
         "evidence": ["Sterling Infrastructure civil construction for hyperscale data center campus development."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "NUE", "company_name": "Nucor",
         "layer": 11, "supply_chain_role": "Structural steel for Meta data center facility construction",
         "bottleneck_score": 62, "evidence_grade": "C",
         "evidence_grade_reason": "Nucor structural steel is a primary input for data center facility construction.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Nucor structural steel supply for data center construction in Meta expansion."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "STLD", "company_name": "Steel Dynamics",
         "layer": 11, "supply_chain_role": "Structural steel supply for Meta data center and campus construction",
         "bottleneck_score": 60, "evidence_grade": "C",
         "evidence_grade_reason": "Steel Dynamics structural steel is consumed in large data center construction builds.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Steel Dynamics structural steel exposure to hyperscale data center construction demand."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "VMC", "company_name": "Vulcan Materials",
         "layer": 11, "supply_chain_role": "Construction aggregates for Meta data center campus development",
         "bottleneck_score": 58, "evidence_grade": "C",
         "evidence_grade_reason": "Vulcan aggregates supply construction sites including hyperscale data center campuses.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Vulcan aggregates for data center campus construction at Meta sites."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "MLM", "company_name": "Martin Marietta Materials",
         "layer": 11, "supply_chain_role": "Construction aggregates for Meta data center campus builds",
         "bottleneck_score": 58, "evidence_grade": "C",
         "evidence_grade_reason": "Martin Marietta aggregates consumed in large data center campus construction.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["Martin Marietta aggregates supply for Meta data center campus construction."],
         "category_name": "Construction & Grid", "category_order": 11},

        {"ticker": "CRH", "company_name": "CRH plc",
         "layer": 11, "supply_chain_role": "Construction materials for Meta data center campus infrastructure",
         "bottleneck_score": 57, "evidence_grade": "C",
         "evidence_grade_reason": "CRH construction materials (cement, aggregates) used in hyperscale data center builds.",
         "relationship_specificity": "category_proxy",
         "themes": ["datacenter_construction", "construction_materials"],
         "evidence": ["CRH construction materials exposure to hyperscale data center campus development."],
         "category_name": "Construction & Grid", "category_order": 11},

        # ── Layer 12: Reality Labs ─────────────────────────────────────────────
        {"ticker": "EL.PA", "company_name": "EssilorLuxottica",
         "tradingview_symbol": "EURONEXT:EL",
         "layer": 12, "supply_chain_role": "Ray-Ban Meta smart glasses exclusive eyewear partner",
         "bottleneck_score": 84, "evidence_grade": "A",
         "evidence_grade_reason": "EssilorLuxottica is the confirmed sole eyewear partner for Ray-Ban Meta smart glasses.",
         "relationship_specificity": "confirmed_partner",
         "themes": ["ar_vr", "wearables"],
         "evidence": ["EssilorLuxottica Ray-Ban Meta smart glasses partnership formally disclosed."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "QCOM", "company_name": "Qualcomm",
         "layer": 12, "supply_chain_role": "Snapdragon XR2/AR1 processors for Meta Quest headsets and smart glasses",
         "bottleneck_score": 82, "evidence_grade": "A",
         "evidence_grade_reason": "Qualcomm Snapdragon XR processors confirmed in Meta Quest headsets and next-gen AR glasses.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "custom_silicon"],
         "evidence": ["Qualcomm Snapdragon XR2/AR1 in Meta Quest 3 and Ray-Ban Meta next-gen AR glasses."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "002241.SZ", "company_name": "Goertek",
         "tradingview_symbol": "SZSE:002241",
         "layer": 12, "supply_chain_role": "Meta Quest headset manufacturing — confirmed OEM",
         "bottleneck_score": 79, "evidence_grade": "A",
         "evidence_grade_reason": "Goertek is confirmed as primary manufacturing partner for Meta Quest VR headsets.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "hardware_manufacturing"],
         "evidence": ["Goertek confirmed Meta Quest VR headset manufacturing partner."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "6758.T", "company_name": "Sony Group",
         "tradingview_symbol": "TSE:6758",
         "layer": 12, "supply_chain_role": "Image sensors for Meta Quest cameras and AR/XR wearables",
         "bottleneck_score": 76, "evidence_grade": "B",
         "evidence_grade_reason": "Sony IMX sensors are used in Meta Quest passthrough cameras and XR wearable modules.",
         "relationship_specificity": "critical_upstream",
         "themes": ["ar_vr", "image_sensors"],
         "evidence": ["Sony IMX image sensors in Meta Quest passthrough and XR camera modules."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "STM", "company_name": "STMicroelectronics",
         "layer": 12, "supply_chain_role": "MEMS sensors and microcontrollers for Meta Quest and wearables",
         "bottleneck_score": 72, "evidence_grade": "B",
         "evidence_grade_reason": "STMicroelectronics MEMS IMUs and microcontrollers used in Meta Quest headset motion tracking.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "mems_sensors"],
         "evidence": ["STM MEMS IMU sensors in Meta Quest headset motion tracking systems."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "000725.SZ", "company_name": "BOE Technology",
         "tradingview_symbol": "SZSE:000725",
         "layer": 12, "supply_chain_role": "OLED/LCD display panels for Meta Quest XR displays",
         "bottleneck_score": 70, "evidence_grade": "B",
         "evidence_grade_reason": "BOE Technology supplies display panels for Meta Quest VR headset display systems.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "display_panels"],
         "evidence": ["BOE display panel supply for Meta Quest VR headset XR display systems."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "034220.KS", "company_name": "LG Display",
         "tradingview_symbol": "KRX:034220",
         "layer": 12, "supply_chain_role": "OLED microdisplay panels for Meta XR/AR next-generation headsets",
         "bottleneck_score": 68, "evidence_grade": "B",
         "evidence_grade_reason": "LG Display OLED micro-panel technology supply for Meta next-generation AR/VR headsets.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ar_vr", "display_panels"],
         "evidence": ["LG Display OLED supply for Meta XR headset display systems."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "2382.HK", "company_name": "Sunny Optical Technology",
         "tradingview_symbol": "HKEX:2382",
         "layer": 12, "supply_chain_role": "Optical lenses and camera modules for Meta Quest and AR glasses",
         "bottleneck_score": 67, "evidence_grade": "B",
         "evidence_grade_reason": "Sunny Optical supplies precision optics and camera modules for Meta XR products.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "optics"],
         "evidence": ["Sunny Optical precision lenses and camera modules for Meta Quest and AR glasses."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "2018.HK", "company_name": "AAC Technologies",
         "tradingview_symbol": "HKEX:2018",
         "layer": 12, "supply_chain_role": "Audio acoustics and haptics for Meta Quest headsets",
         "bottleneck_score": 65, "evidence_grade": "B",
         "evidence_grade_reason": "AAC Technologies supplies micro-speakers, receivers and haptic actuators for Meta Quest.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "audio_haptics"],
         "evidence": ["AAC Technologies audio and haptic components in Meta Quest headset devices."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "HIMX", "company_name": "Himax Technologies",
         "layer": 12, "supply_chain_role": "Display drivers and WLO optics for Meta XR microdisplays",
         "bottleneck_score": 64, "evidence_grade": "B",
         "evidence_grade_reason": "Himax display drivers and wafer-level optics used in Meta XR headset display system.",
         "relationship_specificity": "confirmed_supplier",
         "themes": ["ar_vr", "display_panels"],
         "evidence": ["Himax display drivers and WLO optics in Meta XR headset display modules."],
         "category_name": "Reality Labs", "category_order": 12},

        {"ticker": "KOPN", "company_name": "Kopin Corporation",
         "layer": 12, "supply_chain_role": "Microdisplay technology for Meta AR glasses and XR headsets",
         "bottleneck_score": 60, "evidence_grade": "B",
         "evidence_grade_reason": "Kopin CyberDisplay microdisplay technology used in Meta AR glasses development.",
         "relationship_specificity": "strong_proxy",
         "themes": ["ar_vr", "microdisplays"],
         "evidence": ["Kopin CyberDisplay microdisplay supply for Meta AR glasses and XR headset development."],
         "category_name": "Reality Labs", "category_order": 12},

        # ── Layer 10 addition ─────────────────────────────────────────────────
        {"ticker": "GOOGL", "company_name": "Alphabet / Google",
         "layer": 10, "supply_chain_role": "Google Cloud capacity contracts for Meta AI workload overflow and hybrid compute",
         "bottleneck_score": 87, "evidence_grade": "B",
         "evidence_grade_reason": "Meta confirmed cloud capacity partnership with Google for AI overflow compute; publicly reported agreements.",
         "relationship_specificity": "ecosystem_partner",
         "themes": ["cloud_capacity", "ai_compute"],
         "evidence": ["Alphabet/Google Cloud capacity contracts with Meta for AI workload overflow and hybrid cloud strategy."],
         "category_name": "Neocloud & Leased Compute", "category_order": 10},

        # ── Layer 4 addition ─────────────────────────────────────────────────
        {"ticker": "MXL", "company_name": "MaxLinear",
         "layer": 4, "supply_chain_role": "PAM4 DSP and connectivity ICs for Meta AI networking fabric",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "MaxLinear XBAR and PAM4 DSP ICs present in Meta data-center network line cards.",
         "relationship_specificity": "ecosystem_member",
         "themes": ["ai_networking", "semiconductor_components"],
         "evidence": ["MaxLinear connectivity semis used in Meta data-center networking switch and line-card infrastructure."],
         "category_name": "AI Networking", "category_order": 4},

        # ── Layer 5 addition ─────────────────────────────────────────────────
        {"ticker": "6961.T", "company_name": "Enplas",
         "tradingview_symbol": "TSE:6961",
         "layer": 5, "supply_chain_role": "Micro-lens arrays and IC test sockets for optical transceiver and silicon photonics",
         "bottleneck_score": 70, "evidence_grade": "C",
         "evidence_grade_reason": "Enplas micro-lens arrays and test sockets used in optical transceiver and silicon photonics components for Meta AI networking.",
         "relationship_specificity": "ecosystem_member",
         "themes": ["optical_networking", "test_equipment"],
         "evidence": ["Enplas micro-lens array and test socket components for optical transceiver and silicon photonics in Meta AI networking."],
         "category_name": "Optical Networking", "category_order": 5},

    ],
}
